### ISSUE TITLE
Make favicons URLs relative

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#1]
Look at the URLs in view-source:https://landscapeapp.netlify.com/cncf/format=landscape

All of them should use relative URLs so that we can effectively QA changes at https://landscapeapp.netlify.com/cncf/format=landscape

**Comment by ZeusTheTrueGod** [comment]
@dankohn please review! favicon is fetched properly, and relative urls are used everywhere.
for twitter and facebook meta tags I have not made changes, they do not affect the page rendering

**Comment by dankohn** [comment]
LGTM. But can we get rid of https://github.com/cncf/landscapeapp/blob/master/tools/updateIndexFile.js#L20-L28

**Comment by ZeusTheTrueGod** [comment]
Thanks, we do not need this file anymore
