### ISSUE TITLE
Add SVG Cropping tests

### ISSUE THREAD

**Issue by ZeusTheTrueGod** [cncf/landscapeapp#10]
Copy the original and cropped versions of kubevirt.svg and deep-framework.svg into a fixtures directory and add a test that confirms that the cropping code produces the cropped version. This will allow us to avoid regressions if we have to modify the cropping code in the future.

**Comment by dankohn** [comment]
Closed with 601b726d61dfe5fd03ed20f11bff3dea72a27df8
