### ISSUE TITLE
Not filtering out fonts

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#106]
This SVG is still listing a lot of fonts. Please figure out if it could have been optimized further.

https://github.com/LFDLFoundation/lfdl-landscape/blob/master/hosted_logos/uima.svg
https://landscape.lfdl.io/logos/apache-uima.svg

**Comment by ZeusTheTrueGod** [comment]
The problem here is that while the text was converted to glyphs, its style is still present.
I'll add a custom svgo plugin to get rid of those non used elements

**Comment by dankohn** [comment]
Great.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
While I am able to properly handle this case, when there is a `... style={font-weight: 500} ` like style attribute, I 'm not able to handle the
` <style> a.b { font-weight: 500} <style> ` declaration, or it may be too complex to handle it.

**Comment by dankohn** [comment]
I've asked @alexcontini to convert the fonts to paths of the original SVG using Illustrator. If it does an acceptable job and avoid embedding the font info, than an alternative option would just be to fail on XML with a `font-family` attribute.

**Comment by ZeusTheTrueGod** [comment]
I am able to properly handle this file, look at the latest commit. The only problem which we had is  that we have obsolete attributes and thus it takes a bit of extra space. I'm able to remove all those extra attributes and inline styles

**Comment by ZeusTheTrueGod** [comment]
Anyway, that is done in the svg-autocrop

**Comment by ZeusTheTrueGod** [comment]
Reopening, because I need a PR to reference a latest svg-autocrop.
Also, I'd like to run this on all the cncf files to see how many files are affected

**Comment by dankohn** [comment]
Closed with https://github.com/cncf/svg-autocrop/commit/65be70d2660a0d32c8195b844f25a6a9656a6454#diff-168726dbe96b3ce427e7fedce31bb0bc
