### ISSUE TITLE
Create a service to auto-crop images

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#116]
Create a simple two field form that allow uploading of SVG, AI, or EPS and asks for the name of the project or organization represented by the logo. Output as an autocropped SVG that is auto-downloaded. User interface can be similar to cloudconvert.com but much simpler. Host at svg.cncf.io.

Use Inkscape as the converter. https://github.com/papandreou/node-inkscape
React drag and drop upload: https://github.com/react-dropzone/react-dropzone

**Comment by ZeusTheTrueGod** [comment]
Fantastic task!

**Comment by dankohn** [comment]
You could also use this to host it. I would prefer to get this up and running on a Packet server (maybe the same one as the update server), rather than Lambda.
