### ISSUE TITLE
Landscape missing URL

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#133]
Under the QR code of https://landscape.cncf.io/ you're supposed to see `l.cncf.io`. https://landscape.cncf.io/format=serverless and https://landscape.lfdl.io/ both have it.

**Comment by ZeusTheTrueGod** [comment]
Should be fixed in the cncf repo via my latest commit with an updated settings.yml

**Comment by dankohn** [comment]
Fixed with https://github.com/cncf/landscape/commit/a9a70500381ff6c4cd10bef38acf78805e71d9e1
