### ISSUE TITLE
Add command line autocropping

### ISSUE THREAD

**Issue by ZeusTheTrueGod** [cncf/landscapeapp#14]
We're now going to change all of our logos on https://www.cncf.io/about/members/ to be SVGs. To help with the process, it would be nice to give @taylorwaggoner access to the autocropping SVG tool you've built.

If she downloads https://cdn.worldvectorlogo.com/logos/red-hat-2.svg to a directory, can you please set it up so that `yarn autocrop red-hat-2.svg` will produce a `red-hat-2-cropped.svg` using our existing autocropping rules.

**Comment by ZeusTheTrueGod** [comment]
What should be done here? We have a `yarn fix` command there which processes all images in the `images` folder

**Comment by dankohn** [comment]
My ideal would be a set of simple instructions that our non-technical
support staff can follow to install Homebrew, `yarn install svg-autocrop`
and then later: `yarn upgrade svg-autocrop` and having `yarn optimize` act
on all files in a folder called input and creating a folder called output
containing optimized files with the same filename. It also needs to fail
with clear errors if there's a font or PNG in the input SVG.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
Ok, so new folder names are `input` and `output`, we already fail with clear errors, and I'll add a readme, we can call it `BatchUsage.txt`

**Comment by dankohn** [comment]
Please just add instructions to the main Readme, as that is what shows up
on https://www.npmjs.com/package/svg-autocrop
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
Done, can we ask Alex to check that it is all clear ?

**Comment by ZeusTheTrueGod** [comment]
That was done in an svg-autocrop repo, now need to get the response from users

**Comment by dankohn** [comment]
@taylorwaggoner and @alexcontini both confirmed the directions worked well for them, so this is done.
