### ISSUE TITLE
What's up with Projet?

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#141]
Why is the #1 clickout from https://analytics.google.com/analytics/web/#/dashboard/RxXkEa0oTwKaCMrYEBq23Q/a114451006w170316499p170146953/ `Projet`?

**Comment by ZeusTheTrueGod** [comment]
It is a typo for a project in a 
```
<OutboundLink eventLabel="projet" to={settings.global.company_url} target="_blank"
```
i.e. when people click on CNCF logo and are navigated to the cncf.io

**Comment by dankohn** [comment]
Fixed with https://github.com/cncf/landscapeapp/commit/54a7fcb264b11326bd94f67088620c0ef09f7125
