### ISSUE TITLE
npm install latest without changing files

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#163]
When we were using yarn, I could do `git pull; yarn update` and fetch the latest NPM modules without modifying `package.json`.

Now, when I run `git pull; npm install interactive-landscape@latest` it almost shows a modified `package.json` with lots of `bundle: true` and `optional: true` lines added. I think this may be because the update server is using an old npm version. I'm using `6.7.0`.

If I have to, I will start doing `git pull; npm install interactive-landscape@latestl; git checkout package-lock.json` but that doesn't seem like it should be necessary.

**Comment by ZeusTheTrueGod** [comment]
The version used by a landscape is a 6.8, so you could add `npm install -g npm` as a first part of your workflow.
```
± |master {1} ✓| → npm install -g npm
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.8.0
added 2 packages from 2 contributors, removed 2 packages and updated 7 packages in 16.26s

|ruby-1.8.7-head| Andreys-MBP-Retina in ~/Documents/cncf
± |master {1} ✓| → npm -v
6.8.0

|ruby-1.8.7-head| Andreys-MBP-Retina in ~/Documents/cncf
± |master {1} ✓| → npm install interactive-landscape@latest

> puppeteer@1.12.2 install /Users/zeus/Documents/cncf/node_modules/interactive-landscape/node_modules/puppeteer
> node install.js

Downloading Chromium r624492 - 84.5 Mb [====================] 100% 0.0s
Chromium downloaded to /Users/zeus/Documents/cncf/node_modules/interactive-landscape/node_modules/puppeteer/.local-chromium/mac-624492
+ interactive-landscape@1.0.141
added 3 packages from 2 contributors, removed 13 packages, updated 100 packages and audited 168521 packages in 188.393s
found 3 vulnerabilities (2 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

|ruby-1.8.7-head| Andreys-MBP-Retina in ~/Documents/cncf
± |master {1} ✓| → git diff
```

**Comment by dankohn** [comment]
That helped, but when I run the `all` command twice, it still seems quite slow the second time. Did yarn just check if `package.json` was installed while `npm` verifies every file?

`alias all='npm install -g npm; for path in /Users/dan/Dropbox/Documents/dev/{landscapeapp,landscape,lfdl-landscape,svg-autocrop}; do git -C $path pull -p; npm --prefix $path run latest; done;'
`
