### ISSUE TITLE
Make CNCF image the same width

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#169]
Please make the CNCF logo the same width as the Landscape logo.

![image](https://user-images.githubusercontent.com/3083270/52933821-8a144680-3322-11e9-82aa-807d3d44930c.png)

**Comment by ZeusTheTrueGod** [comment]
![image](https://user-images.githubusercontent.com/230982/52961283-802a2c00-3392-11e9-9933-0d5a613060f7.png)

Is this enough? Otherwise, if you want to align icons, I'll have to change the svg itself

**Comment by dankohn** [comment]
That's good.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com
