### ISSUE TITLE
Logo distortion

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#178]
Please compare the original https://github.com/cncf/landscape/blob/master/hosted_logos/k3s.svg to the autocropped version https://github.com/cncf/landscape/blob/master/cached_logos/k3s.svg. The original has horizontal gridlines throughout.

But the autocropped version does not: https://landscape.cncf.io/logos/k3s.svg

Cc @taylorwaggoner

**Comment by ZeusTheTrueGod** [comment]
I don't see this as a big deal, but I can compare how much the two images are matching each other, the original and the converted one, and then do not apply a certain optimization

**Comment by dankohn** [comment]
Could you please test whether expanding to 3 or 4 decimal places fixes the problem? If so, it seems like we could make that change without impacting size much at all.

**Comment by dankohn** [comment]
It's an issue with the underlying SVG not scaling seamlessly, which you can see by resizing the browser window. Closing as Won't Fix.
