### ISSUE TITLE
Clean up SVGs before caching

### ISSUE THREAD

**Issue by ZeusTheTrueGod** [cncf/landscapeapp#18]
The goal here is to come up with a standard cleaning module that minimizes the size of SVGs before caching. It can probably use modules from https://github.com/svg/svgo rather than implementing everything itself.

For example, note that running on https://landscape.cncf.io/logos/kubernetes.svg would remove at the Illustrator and Inkscape mentions at the top, along with thockin's home directory.

https://dev.to/adammcquiff/how-and-why-to-clean-svg-markup-49i
As part of the cleanup, please change the title of each SVG to match what we call it in sitemap.xml. E.g., `Kubernetes logo`, `Alibaba Cloud logo`.

We also want to remove all comments and carriage returns in the file.

I believe we can do without XML headers and just use:
```
<svg xmlns="http://www.w3.org/2000/svg"  viewBox="-2.65 4.12 325.52 69.68">
```
Also, viewbox numbers can likely be rounded without having any impact such as `-2.6499999999999773 being `-2.65` and `325.52000000000004` being `325.52`

Other SVG cleaners:
https://www.npmjs.com/package/svg-cleaner
https://github.com/scour-project/

More good advice on cleaning SVGs: https://commons.wikimedia.org/wiki/User:Quibik/Cleaning_up_SVG_files_manually

In particular, please cut out `i:pgf` tags such as those in https://landscape.cncf.io/logos/bloombase.svg

**Comment by dankohn** [comment]
Closed with 601b726d61dfe5fd03ed20f11bff3dea72a27df8
