### ISSUE TITLE
Googlebot sees uncaught syntax error

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#185]
Go to https://search.google.com/u/1/search-console/inspect?resource_id=https%3A%2F%2Flandscape.cncf.io%2F&id=59kZLEJ9t-r4TbdKmxYnuQ&alt_id=zBRUqqgCmh82WNMknL68GA&panel_tab=2 and test a URL like https://landscape.cncf.io/selected=containerd
```
Uncaught SyntaxError: Unexpected token =>
https://landscape.cncf.io/main.6fc8dd7ec0be0b65afbf.js:12
```
Click live test and then more info.

**Comment by ZeusTheTrueGod** [comment]
Not a real issue. With googlebot, we load 2 javascripts, an original one and a special one designed for googlebot. Original one fails with a parsing error, and that is what you see in a console.
