### ISSUE TITLE
Verify SVG displays

### ISSUE THREAD

**Issue by ZeusTheTrueGod** [cncf/landscapeapp#19]
Attached is a corrupt SVG. Can we detect that it fails to display by trying to convert to a PNG and then fail with a fatal error?

[singularity.svg.zip](https://github.com/cncf/landscape/files/1900177/singularity.svg.zip)

**Comment by dankohn** [comment]
Closed with 601b726d61dfe5fd03ed20f11bff3dea72a27df8
