### ISSUE TITLE
Do not allow improper twitter urls

### ISSUE THREAD

**Issue by ZeusTheTrueGod** [cncf/landscapeapp#195]
twitter url should start form https://twitter.com/

**Comment by jordinl83** [comment]
@ZeusTheTrueGod @dankohn what should we do if they don't? Throw an error or silently ignore them?

**Comment by ZeusTheTrueGod** [comment]
We throw an error in these cases, look at `tools/generateJson` , a lot of examples how I collect all the errors, report them and exit
