### ISSUE TITLE
Switch from members.yml to using a Member category

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#200]
We want to replace https://www.cncf.io/about/members/ with a new landscape that will be embedded and look like https://landscape.lfdl.io/category=lf-dl-member-company&format=card-mode&grouping=category&embed=yes.

The main benefit is that it will be less work for us to maintain and we'll be able to show our members on a CNCF Member Landscape (which will be in addition to the cloud native and serverless landscapes).

Please add a third `format` called `logo-mode`. It should work just like `card-mode` except leave out all of the text (product name, company name, funding, and stars).

Rather than getting the members from `members.yml`, you will read them as the sub-categories of the `CNCF Member` category.

**Comment by ZeusTheTrueGod** [comment]
But what about the new CNCF Member category itself, will you fill it manually? Also what should happen when you select an element?

**Comment by ZeusTheTrueGod** [comment]
Also will we have subcategories with a status?

**Comment by ZeusTheTrueGod** [comment]
I'd like to know if this new logo-mode is a hidden one, so it will not have a button to enable it, and instead it will be just a part of an url. I can make an example branch in a cncf just to test those CNCF members.

**Comment by dankohn** [comment]
We want to add a 4th mode (3rd landscape) called `Members`. Creating the data is underway at https://github.com/cncf/landscape/tree/members-landscape.
