### ISSUE TITLE
autocrop doesn't work on all white SVGs

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#204]
Add a special mode to support autocropping all white SVGs like https://github.com/cncf/artwork/blob/master/other/cncf/horizontal/white/cncf-white.svg

If the only colors are white and transparent, then size around the white logo.

**Comment by AndreyKozlov1984** [comment]
So far the problem is that I detect a white background on a pretty small png picture, that is what makes the whole detection working improperly.
