### ISSUE TITLE
GA for Github Page

### ISSUE THREAD

**Issue by AndreyKozlov1984** [cncf/landscapeapp#21]
Please create a separate Google Analytics sub-account and use ga-beacon or similar to show traffic results from https://github.com/cncf/landscape and https://github.com/cncf/landscape/blob/master/README.md

https://github.com/igrigorik/ga-beacon

**Comment by ZeusTheTrueGod** [comment]
@dankohn please specify if this is for a landscapeapp, per project or for landscapeapp and every project
