### ISSUE TITLE
Fix positioning during first load

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#216]
When first painting the screen in landscape mode, it shows CNCF-hosted projects first. Please position them in the spot that they'll be in, so that, for example, gRPC isn't centered in its box.

![image](https://user-images.githubusercontent.com/3083270/59146877-94397e00-89c1-11e9-8fbb-8630f88b2b5a.png)

Then, the non-CNCF projects will be painted into their spots but nothing needs to be moved.

![image](https://user-images.githubusercontent.com/3083270/59146870-7d932700-89c1-11e9-8abf-38e9a9e27af0.png)

This could probably be implemented by adding extra info into `preview.json` of how many empty boxes should be positioned around the graduated and incubating projects in each category. Then, on full paint, each of those empty boxes would be replaced by the actual logo. Also

**Comment by ZeusTheTrueGod** [comment]
I don't think I need this preview.json anymore, @dankohn , can we get rid of it? It helped a lot only in the card mode, so I would either remove it completely, or keep it only for a card mode. preview.json is ignored on anything but a  `/format=card-mode` url

**Comment by dankohn** [comment]
Yes, let's eliminate preview.json.
