### ISSUE TITLE
Create static member landscape 

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#223]
Please create a new static image for `CNCF Members` that shows https://deploy-preview-1201--landscape.netlify.com/category=cncf-members&format=card-mode&grouping=category

For the inset image, please kill the Public Cloud category, move the 3 bottom sections to the left, and put the new inset image below the serverless one.

You can make the changes to the `cncf-members` branch.

[ ] Support `enduser: true`, and then allow enduser=yes filter to show only elements with enduser: true

**Comment by ZeusTheTrueGod** [comment]
As I understand this, for now it is just a 3rd landscape. We don't need its interactive version yet.

**Comment by ZeusTheTrueGod** [comment]
It is not clear yet if you want a card layout for CNCF members or a new landscape though.

**Comment by ZeusTheTrueGod** [comment]
I understand how to change the current 'Landscape' layout, but what exactly is on this inset image - according to your description I should render a card layout

**Comment by dankohn** [comment]
How about using these 4 emoji instead of landscape, card mode, serverless, and member:
🌄  🃏  ️️🙅‍♀  💼

Otherwise, you'll just need to wrap Member and put it below and in between landscape and card mode.

**Comment by ZeusTheTrueGod** [comment]
I would not recognize what is going on here. But I think we could use smaller tabs, dots, and etc.
Server...,Lands..., Card, Members. Or to use a bit smaller font

**Comment by dankohn** [comment]
Outstanding issues:

- [ ] Abbreviate modes on mobile `server...`, `lands...`
- [ ] Apple's badge should say `CNCF Platinum End User Member`
- [ ] When the Crunchbase value is set to `https://www.cncf.io/enduser` please set the company to `Non-Public Unnamed Organization`, headcount to `1-10`, and set the city to `Bouvet Island, Antarctica`. Please sort all of these cards last when sort is alphabetical.

**Comment by dankohn** [comment]
Merged!
