### ISSUE TITLE
Change Hong Kong

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#224]
Please change "Hong Kong, Hong Kong" to "Hong Kong, China".

**Comment by dankohn** [comment]
Also, I don't want to get into the politics of changing it on Crunchbase, but please map `Taiwan, Taiwan` to be `Taiwan, China`.

**Comment by dankohn** [comment]
And please map `Sheung Wan, Hong Kong` to `Hong Kong, China`

**Comment by ZeusTheTrueGod** [comment]
Ok, I'll apply changes inside our code where we process cities

**Comment by ZeusTheTrueGod** [comment]
@dankohn there is `Taipei, Taiwan` and no `Taiwan, Taiwan` at this moment

**Comment by dankohn** [comment]
Please forget this. I'll handle a different way.
