### ISSUE TITLE
Tighten spacing for categories

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#226]
The spacing between categories in the navbar seems to have become double-spaced when it would be much more usable single-spaced.

**Comment by ZeusTheTrueGod** [comment]
Any chance to provide a screenshot? Are you talking about select popup ?

**Comment by dankohn** [comment]
Please fit twice as dense here:

![image](https://user-images.githubusercontent.com/3083270/62656157-96707800-b931-11e9-881b-f676a7d52518.png)
