### ISSUE TITLE
Don't serve node_modules

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#228]
The app is serving hundred of mainly blank pages such as:

https://landscape.cncf.io/core-js/modules
https://landscape.cncf.io/node_modules/@material-ui/core/es/SvgIcon
https://landscape.cncf.io/node_modules/is-in-browser/dist

Can it instead not serve anything from those directories and have them redirect to https://landscape.cncf.io/. Related to #210.

That would allow us to remove the `Disallow` directive from robots.txt.

**Comment by ZeusTheTrueGod** [comment]
I'm not sure you are that this thing exist.
Someone makes a random stupid URL and then refers to it. Of course no real page exist and nothing is returned. But because we may have any random url in our browser, the index.html is served when a random page is requested.

**Comment by dankohn** [comment]
https://landscape.cncf.io/core-js/modules returns an HTML page while https://landscape.cncf.io/xyz correctly redirects to https://landscape.cncf.io/.

I believe you can fix using splats as described in https://www.netlify.com/docs/redirects/.

**Comment by dankohn** [comment]
Redirects added with https://github.com/cncf/landscapeapp/commit/edfbbfb5ff4c0a48404786b69b5ffd08ffad7ffb
