### ISSUE TITLE
Pre-render main 4 views

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#251]
https://github.com/stereobooster/react-snap
https://facebook.github.io/create-react-app/docs/pre-rendering-into-static-html-files

Compare time to first paint with and without.

**Comment by AndreyKozlov1984** [comment]
A very interesting idea

**Comment by dankohn** [comment]
Closed by https://github.com/cncf/landscapeapp/commit/3f1ef1ca6b111f30f0fd1b484a3c89fccd224053
