### ISSUE TITLE
Put labels HTML below other text

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#263]
Googlebot is reading the labels before the description giving it less relevant text to show as a snippet.

Rook [shows](https://www.google.com/search?tbs=ift%3Asvg%2Cimgo%3A1&tbm=isch&sa=1&q=rook+logo+cncf+landscape) the text "CNCF Incubating" when it would preferably show "Rook Cloud Native Computing Foundation (CNCF) Runtime Cloud-Native Storage Storage Orchestration for Kubernetes". Even better would be if you could have the description come first in the HTML (though still show them in the current order) so the text snippet would be:

"Rook Storage Orchestration for Kubernetes Cloud Native Computing Foundation (CNCF) Runtime Cloud-Native Storage Storage"

![image](https://user-images.githubusercontent.com/3083270/61996637-5cb38d80-b064-11e9-9b23-4bfc71c145dc.png)

**Comment by ZeusTheTrueGod** [comment]
![image](https://user-images.githubusercontent.com/230982/62562790-ac226680-b879-11e9-8831-6b99435d355c.png)
How am I suggested to get your description from the screenshot ?

**Comment by ZeusTheTrueGod** [comment]
I can propose to get rid of all the components here in the left part, it does not make sense.
And then keep only top 3 rows as a description.
