### ISSUE TITLE
Set every page as either canonical or noindex

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#264]
Add a tag like:
```xml
<link rel="canonical" https://landscape.cncf.io/selected=argo>
```
to https://landscape.cncf.io/selected=argo

Explanation for why is at https://moz.com/learn/seo/canonicalization

Use the same function that is dynamically applying `noindex` pages. Every page served should either have a `canonical` tag or a `noindex` one.

**Comment by ZeusTheTrueGod** [comment]
According to https://en.wikipedia.org/wiki/Canonical_link_element, we should add this in a case when there are other parameters in the page.
i.e.
`selected=a&x=b` should lead to a `seleted=a` link. Am I correct?
You want to get <link rel="canonical" https://landscape.cncf.io/selected=argo> for a same url, that is strange

**Comment by dankohn** [comment]
I'm trying to address the category of 65 URLs in the Google Search Console of "Duplicate, submitted URL not selected as canonical". When you click the magnifying glass for more details, they show "User-declared canonical: None".

Also, it doesn't seem like it will hurt.
