### ISSUE TITLE
CNCF-hosted projects show as non-member projects

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#271]
See https://landscape.cncf.io/category=certified-kubernetes-installer&format=card-mode

Everything run by CNCF should be listed as a CNCF member project. This may require a new setting in settings.yml to enter `https://www.crunchbase.com/organization/cloud-native-computing-foundation`.

**Comment by ZeusTheTrueGod** [comment]
I.e. if a crunchbase is equal to https://www.crunchbase.com/organization/cloud-native-computing-foundation, I should treat it as a 'member' ? We have a different way to specify membership

**Comment by dankohn** [comment]
Yes, exactly. It's an extra rule. Or we could create an extra category "Subsidiary CNCF Projects" that would capture the bottom five here:

https://landscape.cncf.io/format=card-mode&organization=cloud-native-computing-foundation-cncf

**Comment by ZeusTheTrueGod** [comment]
![image](https://user-images.githubusercontent.com/230982/62429264-8c1d6680-b704-11e9-9307-84ae1169e946.png)

About to make a PR on cncf project, because it is a change only in settings.yml and landscape.yml

**Comment by ZeusTheTrueGod** [comment]
https://github.com/cncf/landscape/pull/1343

**Comment by ZeusTheTrueGod** [comment]
Although CNCF itself  was added to that list too

**Comment by ZeusTheTrueGod** [comment]
@dankohn should I hide the CNCF from that list? We usually display an organization itself as a 'member' in other cases, like here

![image](https://user-images.githubusercontent.com/230982/62429368-e0751600-b705-11e9-8597-b7e3b7c238cc.png)

**Comment by dankohn** [comment]
Correct. CNCF shouldn't be here: https://deploy-preview-1343--landscape.netlify.com/format=card-mode&organization=cloud-native-computing-foundation-cncf&project=hosted,graduated,incubating,sandbox,member&selected=cncf

My preference would be to have no changes to landscape.yml at all and instead just have a new section in settings.yml where you add `self: https://www.crunchbase.com/organization/cloud-native-computing-foundation`

**Comment by ZeusTheTrueGod** [comment]
Ok, I'll switch to self
