### ISSUE TITLE
Quiet Core-JS ad messages

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#277]
https://github.com/zloirock/core-js/issues/548#issuecomment-494112872

**Comment by jordinl83** [comment]
@dankohn should this be closed?

**Comment by dankohn** [comment]
No, you haven't fixed. You only quieted on landscapeapp, but it doesn't carry over to the 6 landscapes, where the noise is actually a problem. You also may want to revert on landscapeapp where we're probably more interested in the messages.

https://app.netlify.com/sites/landscape/deploys/5d6cf02bb7aaf6000bfbce06

**Comment by dankohn** [comment]
Done with project PRs
