### ISSUE TITLE
Add updatebot for aswf-landscape and graphql-landscape

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#284]
Please create an updatebot for https://github.com/AcademySoftwareFoundation/aswf-landscape  and https://github.com/graphql/graphql-landscape. Also, document the exact steps involved and add to the landscapeapp Readme.

Also, create and document a separate Google Analytics accounts for them.

**Comment by dankohn** [comment]
Please also add https://github.com/openmainframeproject/landscape

**Comment by dankohn** [comment]
Also https://github.com/openmainframeproject/omp-landscape

And please add jmertic@linuxfoundation.org to the Google Analytics and Google Search Console accounts for aswf and omp.

**Comment by jmertic** [comment]
@ZeusTheTrueGod  I'm not seeing either of these in my Google Analytics console - can you confirm?

**Comment by dankohn** [comment]
Moved GA to #365
