### ISSUE TITLE
Autocrop breaks IBM Cloud logo

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#293]
https://github.com/cncf/landscape/commit/860aa4a34bf55c54cd88ce8e9642bff49968e2d7?short_path=354f138#diff-354f1384ccc178805a848adc8b95feb3

Figure out why and add the problematic logo as a fixture.

**Comment by AndreyKozlov1984** [comment]
I've added it to fixtures, it works now, probably it was the same issue with non safe transformation or lack of digits in that transformation.

**Comment by AndreyKozlov1984** [comment]
I can reproduce this on autocrop.cncf.io
