### ISSUE TITLE
Create a feature for acquisition data

### ISSUE THREAD

**Issue by caniszczyk** [cncf/landscapeapp#302]
For example, we have a bit of a hack via https://landscape.cncf.io/funding.html

I'd like to see something similar but for acquisitions, i.e., https://landscape.cncf.io/acquisitions.html

For a cursory read, the crunchbase data may support that.

**Comment by dankohn** [comment]
The solution is to track all acquisitions in the YAML, similarly to how we track parents, and then having an acquisitions.html page generated to show changes.

**Comment by jordinl83** [comment]
@caniszczyk @dankohn something like this? https://deploy-preview-529--landscapeapp.netlify.com/cncf/acquisitions

**Comment by caniszczyk** [comment]
I love it! Can you add a typeahead widget so we can filter by name or date?

something like https://www.npmjs.com/package/react-bootstrap-typeahead

**Comment by jordinl83** [comment]
@caniszczyk @dankohn added filtering to acquisitions data https://deploy-preview-529--landscapeapp.netlify.com

**Comment by caniszczyk** [comment]
Awesome love it, #SHIPIT

**Comment by jordinl83** [comment]
Note that some there's some data missing, I didn't realize crunchbase is paginating acquisitions, so right now we're getting at most 10 acquisitions per company. Will fix it tomorrow
