### ISSUE TITLE
Acquisition data should be used for determining sub-organizations

### ISSUE THREAD

**Issue by jmertic** [cncf/landscapeapp#307]
Example:

https://www.crunchbase.com/organization/the-walt-disney-company

All of Disney's acquisitions aren't listed as sub-organizations, so when looking for member projects we miss the acquisition's projects. Right now I can hack around this with the members.yml file, but that's going away ( https://github.com/cncf/landscapeapp/issues/260 ).

**Comment by ZeusTheTrueGod** [comment]
@dankohn does this mean I need to treat every sub-organization as a root organization when deciding about membership? @jmertic any chance to provide a single example ?

**Comment by ZeusTheTrueGod** [comment]
Looks good, except one thing - there is a https://www.crunchbase.com/organization/the-walt-disney-company#section-overview which has all the acquisitions, but somehow the crunchbase used in the old `members.yml` is https://www.crunchbase.com/organization/walt-disney-studios
which is different and has zero acquisitions. Can I use https://www.crunchbase.com/organization/the-walt-disney-company , @jmertic ?

**Comment by dankohn** [comment]
Yes, fine to switch. But, ideally, if walt-disney-studios were set as a subsidiary of walt-disney-company, you would be able to see that pixar is a member if they share a parent.

Cc @jmertic

**Comment by jmertic** [comment]
Agreed - thanks @ZeusTheTrueGod.

**Comment by ZeusTheTrueGod** [comment]
Does this mean I need to go the parent as much as possible, and then check all acquisitions?
Whatever, that logic seems to be too complex, I've just added a check for a company acquisitions.

**Comment by ZeusTheTrueGod** [comment]
https://5d6992eb640e0f000c9fbc8d--landscapeapp.netlify.com/aswf/selected=usd-universal-scene-description

@jmertic @dankohn please check, I think now it works there

**Comment by dankohn** [comment]
It looks correct to me. We can merge and see if this fixes the problem, if you're OK.

**Comment by ZeusTheTrueGod** [comment]
@jmertic that was merged in 260
