### ISSUE TITLE
Switch CI server for landscapeapp

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#316]
Have landscapeapp run on https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/ so that we can use the 10 parallel builds to build each landscape separately. Ideally, use the Netlify Docker [image](https://github.com/netlify/build-image) to ensure compatibility.

**Comment by caniszczyk** [comment]
I did have GitHub Actions enabled for the CNCF org if you want to go that route too:
https://help.github.com/en/articles/about-github-actions#usage-limits

**Comment by dankohn** [comment]
Closing in favor of #379
