### ISSUE TITLE
Speed up render times

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#324]
The render times for the static images on the CNCF landscape are painfully slow:
7:24:19 PM: visiting http://localhost:4000/landscape?preview&version=2019-09-05T23:24:17Z 17e48d1
7:24:19 PM: visiting http://localhost:4000/serverless?preview&version=2019-09-05T23:24:17Z 17e48d1
7:24:19 PM: visiting http://localhost:4000/members?preview&version=2019-09-05T23:24:17Z 17e48d1
7:24:56 PM: visiting http://localhost:4000/landscape?preview&version=2019-09-05T23:24:17Z 17e48d1
7:24:56 PM: visiting http://localhost:4000/serverless?preview&version=2019-09-05T23:24:17Z 17e48d1
7:24:56 PM: visiting http://localhost:4000/members?preview&version=2019-09-05T23:24:17Z 17e48d1
7:25:31 PM: visiting http://localhost:4000/landscape?version=2019-09-05T23:24:17Z 17e48d1
7:26:48 PM: visiting http://localhost:4000/serverless?version=2019-09-05T23:24:17Z 17e48d1
7:27:10 PM: visiting http://localhost:4000/members?version=2019-09-05T23:24:17Z 17e48d1

Could we speed it up by having the first few work in lower resolution?

Those times are from https://app.netlify.com/sites/landscape/deploys/5d71972a3ffc860008a0a55c

**Comment by jordinl83** [comment]
@dankohn what are these times exactly and how do they relate to the actual render time from [landscape.cncf.io](https://landscape.cncf.io)

I noticed netlify has a CDN, are we using it to deliver the images? https://www.netlify.com/products/edge/

Also, we could consider adding cache response headers so the images don't need to be re-fetched on every navigation.

These two suggestions might not fix the issue you mention, but they could improve performance of the site.

**Comment by dankohn** [comment]
We render images like https://landscape.cncf.io/images/landscape.pdf but having Chromium load the page and create a PDF. But first, we create the other images to put in the bottom right corner.

Everything served by Netlify uses their CDN.

Note that the whole site is served on your first load, and then when you navigate the site, nothing new is fetched. The app is "serverless".
