### ISSUE TITLE
Ant Financial not showing as child

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#348]
https://landscape.cncf.io/format=card-mode&grouping=organization&parent=alibaba-cloud should show Alibaba and Ant, since Ant is a subsidiary. The parent shows correctly in `processed_landscape.yml` but not in the above link.

**Comment by jordinl83** [comment]
Not sure if this is an issue with the crunchbase data, but I see both Alibaba Cloud and Ant Financial have parent Alibaba, so Alibaba Cloud is not Ant Financial's parent.

https://landscape.cncf.io/format=card-mode&grouping=organization&parent=alibaba shows Alibaba Cloud and Ant Financial.

**Comment by dankohn** [comment]
That looks like correct behavior, then. Thank you, closing.
