### ISSUE TITLE
settings.yml guide?

### ISSUE THREAD

**Issue by addikt1** [cncf/landscapeapp#349]
I've been using Landscape from pre-Aug 2018 and am now looking at the latest rev ... wow. The combining of the card view with the placemat view results in some new interdepencies. I'm really struggling to understand and tailor the settings.yml file, even after looking at the graphql sample as per the doc. Is there a "schema" or "model" file for it that lays out the possible settings/values, and what all the top-level entries are?

**Comment by dankohn** [comment]
Is your use public? You can look at some of the other landscapes to get a feel for settings.yml: https://github.com/cncf/landscapeapp/blob/master/landscapes.yml

**Comment by addikt1** [comment]
I've just done some preliminary customizing of the graphql one and it no longer renders. I've been looking at the cncf as well, to compare, but some things are not obvious to me, like the `company` attribute. Also, since I'm using this for my own purposes, and my company is not a CNCF member, none of that categorization applies, so I'm having to modify quite a few values. Trying to understand the dependencies of the values from one area to another - and then into landscape.yml - is where I'm stumbling.
I'll look at some of these other ones you referenced and see if I can get something working.

**Comment by dankohn** [comment]
Unfortunately, then, my advice would be to start again from GraphQL and just keep making small changes to see where it's breaking. We only add things to settings.yml when it changes between landscapes, but the format has definitely grown organically, so there's no official format. This issue will probably also be helpful to you once we implement it: https://github.com/cncf/landscapeapp/issues/206

I'm closing for now, but we're happy to support you if you raise other issues.
