### ISSUE TITLE
Improve tree shaking (again)

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#36]
See setting modules to false in "Keeping Babel from transpiling ES6 modules to CommonJS modules" in https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking/

Also, please see if we should be using lodash-webpack-plugin. https://github.com/lodash/babel-plugin-lodash

**Comment by ZeusTheTrueGod** [comment]
Sadly, the plugin just does not work. Even if I enable all options in this plugin, nothing works in the production mode. In development mode all is ok.
