### ISSUE TITLE
Setup Google Analytics for all landscapes

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#365]

**Comment by dankohn** [comment]
Add jmertic@linuxfoundation.org to omp and aswf landscapes.

**Comment by AndreyKozlov1984** [comment]
There are 6 search consoles at this moment:
aswf
cncf
graphql
lfai
lfedge
omp
@dankohn has an access to all 6 landscapes
@jmertic has an access on `aswf`, `omp`

I'm about to add 2 landscapes, hyperledger and cdfoundation, and make @dankohn an admin of both

**Comment by AndreyKozlov1984** [comment]
Done, @dankohn and @jmertic have been added to hyperledger and cdfoundation

**Comment by jmertic** [comment]
@dankohn @AndreyKozlov1984  I didn't see aswf or omp show up in my Google Analytics account - where should I be looking?

**Comment by dankohn** [comment]
https://search.google.com/u/1/search-console/index?resource_id=https%3A%2F%2Flandscape.openmainframeproject.org%2F&hl=en

**Comment by jmertic** [comment]
Perfect - thanks!
