### ISSUE TITLE
Support less favicons

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#366]
Best practices: https://github.com/audreyr/favicon-cheat-sheet

We don't seem to need all the intermediate sizes.

**Comment by dankohn** [comment]
Could you please review what other sites seem to do and we'll replicate that. I'm fine only targeting relative modern browsers.

**Comment by dankohn** [comment]
Can we get by with just these 7 and no `ico` file at all? https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/

**Comment by dankohn** [comment]
And please see https://realfavicongenerator.net/favicon_checker?protocol=http&site=Landscape.cncf.io

**Comment by jordinl83** [comment]
@dankohn  It seems websites still use `favicon.ico` (https://twitter.com/favicon.ico, https://facebook.com/favicon.ico, https://github.com/favicon.ico), so I would say it's better to leave it there. 

Regarding using fewer image sizes, these are generated by [favicons](https://www.npmjs.com/package/favicons) via [favicons-webpack-plugin](https://www.npmjs.com/package/favicons-webpack-plugin). There's no option to generate fewer sizes. I could look into using https://realfavicongenerator.net/favicon_result?file_id=p1dre4khti9vf11schhn136i10ab6 (Note there's a CLI tool) but that would require more configuration and code than what we [currently have](https://github.com/cncf/landscapeapp/blob/master/webpack.config.prod.js#L85-L94).

Regarding https://realfavicongenerator.net/favicon_checker?protocol=https&site=landscape.cncf.io, I'm not sure if the results are reliable, at least the issues about the `favicon.ico` file. I uploaded https://landscape.cncf.io/favicon.ico to https://egy186.github.io/icojs/#demo and it's showing the right sizes for the icon:

<kbd>
<img src="https://user-images.githubusercontent.com/16135423/70343359-62fa1780-1857-11ea-98f5-662cb05c9eaf.png" alt="Screenshot"/>
</kbd>

**Comment by dankohn** [comment]
We configure here: https://github.com/cncf/landscapeapp/blob/d34ce88d90436bc90a6cde5ab24be35fa6fa9954/webpack.config.prod.js#L85-L95

Can we please exclude all but what's needed for the evergreen browsers? I'm fine keeping favicon.ico as well.
