### ISSUE TITLE
Can we fix this build issue?

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#374]
Generating minified bundle. This will take a moment...
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Webpack Bundle Analyzer saved report to /Users/dan/Dropbox/Documents/dev/landscape/dist/report.html

**Comment by AndreyKozlov1984** [comment]
We control all the output now and transform it in order to get rid of password strings. Thus I could just hide this from logs.
