### ISSUE TITLE
Scale text with browser zoom

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#378]
This is at 67% zoom.

![image](https://user-images.githubusercontent.com/3083270/66078313-c7cf8380-e52f-11e9-930e-8221ecf5ca01.png)
![image](https://user-images.githubusercontent.com/3083270/66078351-de75da80-e52f-11e9-843b-1d4411f011d1.png)

**Comment by AndreyKozlov1984** [comment]
Is this Chrome or Safari? I get this in Chrome only on 50% zoom

**Comment by dankohn** [comment]
Chrome. But can't we get the text to scale to fit correctly at any zoom?

**Comment by AndreyKozlov1984** [comment]
I'm trying different approaches, Chrome does not want to render fonts properly for in a 5-10 px range, I'm looking for a best fix for that.

**Comment by AndreyKozlov1984** [comment]
It certainly works if I embed it inside an SVG, so I'll try this approach first.

**Comment by AndreyKozlov1984** [comment]
Ok, so with SVG it is possible, i.e. I can change the size whatever the zoom is, but I'll have to manually split the text by lines, that is not something I like a lot.

**Comment by AndreyKozlov1984** [comment]
`transform: scale` seems to be a good solution in Chrome. Probably, that is a Chrome only issue, so I'll keep a previous approach for other browsers.
