### ISSUE TITLE
Exception thrown when processing SVG

### ISSUE THREAD

**Issue by jordinl83** [cncf/landscapeapp#380]
An exception is being thrown when processing [colour.svg](https://github.com/AcademySoftwareFoundation/aswf-landscape/blob/37b118acad6496025b0f272b5ceaab899c0d7fba/hosted_logos/colour.svg).

Also the exception is not being handled correctly which, in turn, throws another exception:

```
7:52:41 PM: TypeError: Cannot read property 'substring' of undefined
7:52:41 PM:     at substring (/opt/build/repo/node_modules/interactive-landscape/tools/fetchImages.js:154:107)
```

Commenting out the code that throws the second exception, the original exception was:

```
Error in parsing SVG: Unbound namespace prefix: "serif"
```

See PR https://github.com/AcademySoftwareFoundation/aswf-landscape/pull/34

**Comment by jordinl83** [comment]
Don't think there's anything to do on `landscapeapp`.

The issue was that the error on `svg-autocrop` wasn't handled correctly and the error thrown was:

```
3:08:33 PM: TypeError: Cannot read property 'substring' of undefined
3:08:33 PM:     at substring (/opt/build/repo/node_modules/interactive-landscape/tools/fetchImages.js:154:107)
```

The error that's showing now is:

```
error:  No cached entry, and Colour has issues with logo: colour.svg, Error in parsing SVG: Unbound namespace prefix: "serif"
Line: 0
Column: 91
Char: >
```

**Comment by dankohn** [comment]
That's fine. Assigning to @AndreyKozlov1984

**Comment by AndreyKozlov1984** [comment]
Works on autocrop.cncf.io
