### ISSUE TITLE
Only use ASCII characters in filenames

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#387]
This doesn't seem to be causing any problems yet, but there's no need to use UTF-8 filenames. Could you please convert or remove so filenames are just ASCII.

https://github.com/openmainframeproject/omp-landscape/blob/master/cached_logos/universität-leipzig.svg

**Comment by AndreyKozlov1984** [comment]
I'm going to use https://github.com/fedeguzman/remove-accents-diacritics to replace letters like `û` to `u`, and if there are non ascii letters after the change, I'm going raise an error

**Comment by jordinl83** [comment]
@AndreyKozlov1984 I think you can use https://lodash.com/docs/4.17.15#deburr

**Comment by AndreyKozlov1984** [comment]
Thanks, I'll use it. This will not save us from cyrillic or other special utf-8 characters though, I'll check if I can keep only ascii after that.

**Comment by AndreyKozlov1984** [comment]
I see there is an easy check of ASCII only, https://stackoverflow.com/questions/14313183/javascript-regex-how-do-i-check-if-the-string-is-ascii-only/14313213, so if _.deburr does not help, I'll raise an error.

**Comment by dankohn** [comment]
deburr is a funny function name: https://www.lexico.com/en/definition/deburr

**Comment by jordinl83** [comment]
It's a weird name indeed. 

I wonder if, instead of removing non-ASCII characters, it would be better for us to always generate the file name with something like `${lodash.kebabCase(item.name)}.svg`

**Comment by dankohn** [comment]
We already do kebab-case. We're suggesting to first deburr.
