### ISSUE TITLE
Avoid 30 second timeouts

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#393]
1. Change the `header` at the bottom of `settings.yml` to `foodbar`
2. Run `y test`.
3. It takes more than a minute for tests to timeout and fail

Can we instead check that page has loaded and then check for the expected test, so that the test will fail more quickly?

**Comment by AndreyKozlov1984** [comment]
We certainly need this timeout for netlify builds. More than that, tests itself are not the longest part of the build, and they are run in parallel with rendering landscapes and checking landscapes, thus the slowest part is rendering a full landscape for a CNCF

**Comment by dankohn** [comment]
My point is that a timeout is sub-optimal use of Puppeteer. Instead, you can wait for processing to finish and then check.

See https://docs.browserless.io/blog/2018/06/04/puppeteer-best-practices.html for some related tips.
