### ISSUE TITLE
Contributor count fluctuating to 0

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#395]
Search for `contributors_count: 0` in https://github.com/cncf/landscape/commit/a18b61cae50568689fe0c00050575d0d0f551c60#diff-ea4f83e4d8108e8fdb17ec90794f9bdf. There are 14 times a project is going either to or from zero, which should basically never happen. 

Are we using https://stackoverflow.com/a/44347632/1935918 to count commits or some buggier algorithm?

**Comment by jordinl83** [comment]
Stopping for now to focus on jobs feed.

For reference, the contributors count comes from scraping GH, but GH makes an AJAX request to fetch count so maybe we need to wait until the request is finished.

**Comment by dankohn** [comment]
Let's considering switching from scraping to the pagination trick I link to, which should only require one API call.

**Comment by AndreyKozlov1984** [comment]
@dankohn are you and @jordinl83 working on this? If you have a pagination trick, please mention it somehow.

**Comment by dankohn** [comment]
No, please take it because @jordinl83 is doing a task for cncf.io. Pagination trick is to look at the `last` header as explained here: https://stackoverflow.com/a/44347632/1935918

**Comment by dankohn** [comment]
Though a comment says it doesn't work, so, please verify first.

**Comment by jordinl83** [comment]
Don't think we can use the API to fetch the contributors count:

> GitHub identifies contributors by author email address. This endpoint groups contribution counts by GitHub user, which includes all associated email addresses. To improve performance, only the first 500 author email addresses in the repository link to GitHub users. The rest will appear as anonymous contributors without associated GitHub user information.

But instead of visiting the repo page to find the contributors count, we can just visit the endpoint that returns the actual count. So instead of using https://github.com/tensorflow/tensorflow, we can use https://github.com/tensorflow/tensorflow/contributors_size

**Comment by dankohn** [comment]
Very cool. How did you find about about the URL https://github.com/tensorflow/tensorflow/contributors_size?

**Comment by jordinl83** [comment]
I disabled javascript and for some projects instead of showing the actual count it showed "Fetching contributors". When I inspected that element I saw: `<include-fragment src="/tensorflow/tensorflow/contributors_size">`
