### ISSUE TITLE
Openmainframe no longer getting CNCF-Bot updates

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#398]
https://github.com/openmainframeproject/omp-landscape/commits/master

**Comment by AndreyKozlov1984** [comment]
@dankohn , according to logs, both on a server in `omp.log` file and in our slack channel, the issue is with data:
```
No city for a crunchbase entry for marist-college at https://www.crunchbase.com/organization/marist-college 
Using cached entry, because can not fetch: red-hat Can't resolve stock ticker RHT; please manually add a "stock_ticker" key to landscape.yml or set to null
```

**Comment by dankohn** [comment]
Thanks, I had missed that. Is it possible to add a red color to failing messages, like Netlify does? If so, please open a new issue for that.

**Comment by dankohn** [comment]
CNCF-Bot updates resumed once Crunchbase errors were resolved.
