### ISSUE TITLE
Spurious error: functions preparation step

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#399]
```
5:27:56 PM: Skipping functions preparation step: no functions directory set
```
https://app.netlify.com/sites/lfenergy/deploys/5da3958e4398e50008195e94

Can we remove the error?

**Comment by AndreyKozlov1984** [comment]
I've asked their tech support team if we have any control over that.

**Comment by AndreyKozlov1984** [comment]
We can not do anything at all, according to their response.
