### ISSUE TITLE
Truncated error

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#406]
https://github.com/graphql/graphql-landscape/pull/27#issuecomment-542478997

>No cached entry, and can not fetch: homeaway

The error should have been:

https://app.netlify.com/sites/graphql-landscape/deploys/5da67ab70b6e9b000b06e39b
> 10:10:43 PM: No cached entry, and can not fetch: homeaway Can't resolve stock ticker AWAY; please manually add a "stock_ticker" key to landscape.yml or set to null

**Comment by brianwarner** [comment]
Thanks @dankohn, I appreciate help triaging this one.  I was not sure what that error meant.
