### ISSUE TITLE
yarn outdated shows lots to upgrade

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#41]

**Comment by ZeusTheTrueGod** [comment]
I need to pause this for a while, first, we can not update to latest connected-react-router, next, there is something wrong with running a build on a netlify image after all the upgrades.

**Comment by ZeusTheTrueGod** [comment]
More research shows that a docker based netlify build works differently than a build made on my Mac, and it is also related with a connected-react-router, which does not receive the store and everything fails

**Comment by ZeusTheTrueGod** [comment]
Need to try again with updating packges one by one

**Comment by ZeusTheTrueGod** [comment]
Everything works well if I run it from the update server, so somehow I get a different build only because it is from a netlify build image

**Comment by ZeusTheTrueGod** [comment]
I was able to reproduce an issue on my local machine  after disabling minimization and certain optimizations.
