### ISSUE TITLE
Undefined type error

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#416]
Running `yf` on https://github.com/graphql/graphql-landscape/compare/dankohn-undefined-type-error produces:
```
Fetching images
....................................................................................TypeError: Cannot read property 'substring' of undefined
    at substring (/Users/dan/Dropbox/Documents/dev/graphql-landscape/node_modules/interactive-landscape/tools/fetchImages.js:153:101)
```
Can you please generate a better error.

**Comment by AndreyKozlov1984** [comment]
A very interesting thing, as you see, that error was on landscapeapp version 294, and on landscapeapp version 298 it would have to disappear, but it did not. i.e. `npm run latest` did not help, so a problem was that babel-node stores cached version of old package versions.

**Comment by dankohn** [comment]
Fixed with https://github.com/cncf/landscapeapp/commit/4a4a68defe0ce4c68b57ebce515cfac901affbe1. Now error message is clear.
