### ISSUE TITLE
Bad Twitter should not cause `yarn update` to fail

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#418]
One bad Twitter account causes the whole update to fail. Instead, it should succeed, and just post the error as it is now.

**Comment by AndreyKozlov1984** [comment]
Could you provide more details? If it is an absolutely bogus twitter url, we fail with a fatal error.

**Comment by dankohn** [comment]
The point is that hundreds of other updates will not get made because of one bad Twitter. When we're running nightly updates, can we please treat these sorts of errors as non-fatal.

When doing first deploys, fatal errors are appropriate to get things fixed.

**Comment by AndreyKozlov1984** [comment]
We have two types of checks: first is that twitter url is valid and second that we can fetch data and it is not an empty twitter without tweets. I'll keep checking that a twitter url itself is valid, but will allow issues with fetching data when this data is in a cache.

**Comment by AndreyKozlov1984** [comment]
Actually, that is already how this works at this moment, I'm not even sure we can handle this properly, @dankohn , the only option is to treat all twitter issues as warnings.

**Comment by dankohn** [comment]
Closing for now. I'll reopen if I can suggest a class of errors to ignore.
