### ISSUE TITLE
LFAI not showing 'LF Project' badge

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#425]
What is missing in [settings.yml](https://github.com/lfai/lfai-landscape/blob/master/settings.yml) to get LFAI to show the LF Project badge?

https://landscape.lfai.foundation/format=card-mode&project=hosted&selected=acumos does not show it.

https://landscape.lfai.foundation/format=card-mode&grouping=organization&parent=linux-foundation looks correct.

**Comment by dankohn** [comment]
It looks like CNCF also lost the `LF Project` badge. https://landscape.cncf.io/selected=ti-kv

**Comment by jordinl83** [comment]
@dankohn it seems that the parent tag was removed https://github.com/cncf/landscapeapp/commit/05f31f8df107c2b1f5a8e324667e037aae94770d#diff-7dabb9d7d70ed8587ad2bd4f3a382370. Not sure why... I'll add it back
