### ISSUE TITLE
Download language and commit data in the CSV

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#432]

**Comment by AndreyKozlov1984** [comment]
How exactly? Languages - "Javascript - 75%; Nodejs - 1%; Other: 1%" ? Commit data - how exactly would you like to see this? "23;34;45;54;0;0;0;0....;34" 51 items ?

**Comment by AndreyKozlov1984** [comment]
What about total commits per year?

**Comment by dankohn** [comment]
OK, as part of https://github.com/cncf/landscapeapp/issues/433
