### ISSUE TITLE
Don't truncate license badges

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#440]
https://landscape.cncf.io/format=card-mode&grouping=license&license=open-source&selected=danm

![image](https://user-images.githubusercontent.com/3083270/67783015-f9107600-fa3f-11e9-930d-d334f1f763f3.png)

Please try to move the second column of badges to the left and, if still necessary, shrink the font.

**Comment by AndreyKozlov1984** [comment]
I can detect that there is not enough of space, and then, may be, use 2 rows

**Comment by dankohn** [comment]
I think just moving the badges to the left may free up enough room.

**Comment by AndreyKozlov1984** [comment]
![image](https://user-images.githubusercontent.com/230982/68082610-d2bf5180-fe16-11e9-8c57-d632cb51fd07.png)

**Comment by AndreyKozlov1984** [comment]
I can make it 2 lines with a smaller font if I find that is not enough space.

**Comment by AndreyKozlov1984** [comment]
I'm closing the issue
