### ISSUE TITLE
Make language legend clickable

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#446]
![image](https://user-images.githubusercontent.com/3083270/68024071-65c58380-fc7f-11e9-8a3c-00523895840c.png)

Clicking Python on https://landscape.cncf.io/format=card-mode&selected=envoy should take you to https://landscape.cncf.io/format=card-mode&grouping=language&language=Python.

Please ensure that `C++` and `C#` are properly encoded to work correctly.

**Comment by AndreyKozlov1984** [comment]
That feature is available to everyone, so I'll either need to add a 'Group by language' option to the grouping list, or to write a code to display a group by option when it is not even in a list of available options.

**Comment by AndreyKozlov1984** [comment]
![image](https://user-images.githubusercontent.com/230982/68073950-77954c80-fd8d-11e9-890c-d7e09527a162.png)
