### ISSUE TITLE
Further ways to speed up mobile devices.

### ISSUE THREAD

**Issue by AndreyKozlov1984** [cncf/landscapeapp#460]
The goal is to speed up a loading of a first screen on mobile devices and, optionally, make it faster for a further usage.

![image](https://user-images.githubusercontent.com/230982/68599570-b4052e80-0498-11ea-81db-8170f05f7f30.png)

Here is my ideas how we can throw everything away.
1) Let's load only that javascript which is required to interact on this page. For example, when a user clicks on "Menu" icon in the top left, that script should be downloaded and executed, or when a user clicks on "-" or even on a product element. No need to download and parse and execute the whole javascript bundle at once. Same with "Cards" or "Members" - that all can be postponed until a user clicks on the link.
2) While we already prerender a page, it would be possible to embed svg images for first rows and columns, to speed up rendering a little more.
3) Only the css style required for a first screen should be loaded on a mobile device. It will be embedded in the html page. 
4) The landscape itself could be simplified more for mobile devices. No need for drawing shadows, for example. We could convert the normal 2000x2000 landscape, because it is hard to scroll it, to a simple 600x4000 landscape without a horizontal scroll, where sections are  put in one column. Or a card mode should be used by default on mobile devices, currently it is not easy to scroll even when there are no performance issues.

**Comment by AndreyKozlov1984** [comment]
@dankohn please comment.

**Comment by jordinl83** [comment]
I recommend starting with adding cache control headers, so the SVGs don't need to be downloaded on page refreshes or on different visits...

**Comment by AndreyKozlov1984** [comment]
I thought netlify already does this, if it does not though, we need a hash in the filename to allow far future expire and to keep the file in the cache forever

**Comment by jordinl83** [comment]
Actually, it's not as bad as I thought. I was seeing full refreshes because I had the developer console open with the cache disabled. 

But by default, the response headers are set to `cache-control: public, max-age=0, must-revalidate`. Which means that the logos are not fetched every time, but still a request needs to be made to check if a logo changed. So maybe setting `max-age= 31536000` would help?

**Comment by dankohn** [comment]
We can't set the max age to be high unless we do image fingerprinting like Rails does, where the URL for every image is its hash. Any concerns on doing so?

Webpack seems to support it. https://webpack.js.org/guides/asset-management/#loading-images

**Comment by AndreyKozlov1984** [comment]
I still want to address the first load of our page, where cache is not relevant at all.
