### ISSUE TITLE
Removing platinum member breaks spacing

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#461]
What's strange is that removing a platinum member causes the rest of them to expand to the right and no longer fit. It seems like a bug.

https://github.com/cncf/landscape/pull/1472/files
https://app.netlify.com/sites/landscape/deploys/5dcb05b51c3c3600089110ad

While, by contrast, adding a new item to gold still has them fit. Also, if I remove fit_width: true then it fits but is far to the left.

**Comment by jordinl83** [comment]
Is this issue resolved?

**Comment by dankohn** [comment]
Yes, thank you. The solution was the use of `offset` here: https://github.com/cncf/landscape/commit/809ba066b1bd44ec5b1acf910d53f2ba0b6d0582#diff-98126fffe52a5bcbb73fa2926d7732ddR405

Arguably, we should redo the rendering logic to squeeze logos more tightly without using offset, but I'm not sure it's a common enough problem to worry about.
