### ISSUE TITLE
Comment posting error

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#464]
https://app.netlify.com/sites/landscape/deploys/5dd41b9ef2fe4e000a1154f9

**Comment by dankohn** [comment]
Another one: https://app.netlify.com/sites/lfailandscape/deploys/5dd7f94bec6bc0000b04b0c5

**Comment by dankohn** [comment]
Please also see why this update failed: https://cloud-native.slack.com/archives/CM3Q37KPY/p1574404534000500

**Comment by AndreyKozlov1984** [comment]
Ok, so the original issue is that we run both `branch deploy` and `deploy preview`
![image](https://user-images.githubusercontent.com/230982/69618679-344b9800-1032-11ea-8dac-63305d9b0e0e.png)
And I get a PR number only for one of that (deploy preview). So I'm about to suppress the notification for a branch deploy type of builds, while really we should just to disable those builds in netlify.

**Comment by dankohn** [comment]
Sometimes I like looking at those builds in Netlify, when work is in progress but a PR isn't open yet.

**Comment by AndreyKozlov1984** [comment]
Ok, fine, then I'll just will not attempt to report an error when there is no PR
