### ISSUE TITLE
Create landscape photomosaic

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#465]
Use photomosaic software to take all CNCF-hosted projects and organize in an image of the CNCF logo. Also, try taking all logos on the landscape and generate the landscape logo.

https://en.wikipedia.org/wiki/Photographic_mosaic

**Comment by jordinl83** [comment]
Investigating different options:

## [Metapixel](https://github.com/schani/metapixel/tree/v1.0)

Metapixel is quite slow, first we need to convert all SVGs to PNGs and then generate the mosaic. I tried a couple of approaches:

#### Regular mosaic with 24x24 tiles:

![mosaic-24-square](https://user-images.githubusercontent.com/16135423/70711982-18f3b480-1ce3-11ea-917a-3d303a0e7295.png)

#### Collage with 24x24 tiles (also slower):
![mosaic-24-collage](https://user-images.githubusercontent.com/16135423/70711979-185b1e00-1ce3-11ea-9974-d5d9a784068c.png)

**Comment by jordinl83** [comment]
The following are not actual photomosaics. They are just HTML pages with the logo as background image and on top of that a grid with all the logos. This approach does not require converting SVG to PNG, we can just use the SVGs, plus it allows zooming in arbitrarily.

#### CNCF Logo
![Screenshot 2019-12-11 at 11 02 07](https://user-images.githubusercontent.com/16135423/70712430-134a9e80-1ce4-11ea-8313-21b3ff99e399.png)

#### Landscape Logo
![Screenshot 2019-12-11 at 11 34 39](https://user-images.githubusercontent.com/16135423/70712431-134a9e80-1ce4-11ea-9c85-0f02eecea349.png)

**Comment by jordinl83** [comment]
## [worldveil/photomosaic](https://github.com/worldveil/photomosaic)

Lot's of repeated logos...

![cncf-logo-24](https://user-images.githubusercontent.com/16135423/70729711-f9b94f00-1d03-11ea-87f4-f5ff02525103.jpg)

**Comment by jordinl83** [comment]
## [nuno-faria/tiler](https://github.com/nuno-faria/tiler)

Got stuck...

```
Loading tiles
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1293/1293 [01:28<00:00, 14.68it/s]
Gettting and processing boxes
  0%|                                                                                                          | 0/5 [00:00<?, ?it/s]
```

**Comment by jordinl83** [comment]
## Experimenting with a custom algorithm

#### CNCF Logo

![cncf-mosaic](https://user-images.githubusercontent.com/16135423/70929171-bf68ee00-2032-11ea-8428-6d1d57a3f853.png)

#### Landscape Logo

![landscape-mosaic](https://user-images.githubusercontent.com/16135423/70929181-c4c63880-2032-11ea-95bc-be3b38180683.png)

**Comment by dankohn** [comment]
This was really well done, and I appreciate the multiple approaches. I'm going to close unmerged for now, but we may revisit later.
