### ISSUE TITLE
Add Google Analytics and Webmaster console for all landscapes

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#466]
Please add me to all and dlopez@linuxfoundation.org to the CDF one.

**Comment by danlopez00** [comment]
Thanks @dankohn !

**Comment by jmertic** [comment]
+1 for this - would be really helpful in showcasing the value of these landscapes.

**Comment by AndreyKozlov1984** [comment]
All 10 properties have @dankohn with a full access
The CDF one also has @danlopez00 with a full access.

**Comment by dankohn** [comment]
Great. And could you please add jmertic@linuxfoundation.org for ASWF and OMP.

**Comment by AndreyKozlov1984** [comment]
He is already there with a full access

**Comment by jmertic** [comment]
So I have access to stats through Google Search Console, but not Google Analytics.

**Comment by AndreyKozlov1984** [comment]
Ok, I'll need to add a script and a `UA-...` identifier to the index page and then setup google analytics pages.

**Comment by AndreyKozlov1984** [comment]
All landscapes had been added to google analytics, after a daily update it will start collecting data. @jmertic has been added to OMP and ASWF as an admin.

**Comment by AndreyKozlov1984** [comment]
Done for all landscapes
