### ISSUE TITLE
Fail when project-related projects are not owned by the project

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#495]
https://github.com/cdfoundation/cdf-landscape/commit/2924f6640e04e484644f32fdbb09480240d5d872

This update should have failed to build because the project status was changed by ownership was not changed to CDF. Please add an additional build check.

**Comment by jordinl83** [comment]
@dankohn is ownership determined via Crunchbase data?

**Comment by dankohn** [comment]
Yes
