### ISSUE TITLE
Font config errors

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#496]
Please investigate these fontconfig errors on Netlify.

2:19:04 PM: Fetching images
2:19:15 PM: Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
2:19:15 PM: Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
2:19:15 PM: Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
2:19:15 PM: Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
2:19:15 PM: Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"

**Comment by jordinl83** [comment]
These come from `svg-autocrop`. I think it's fine to ignore these, but @AndreyKozlov1984 knows more about `svg-autocrop` so he should confirm it. 

The line that's causing the verbose debugging is [this one](https://github.com/cncf/svg-autocrop/blob/master/index.js#L433), removing `dumpio: true` silences the warning.

**Comment by jordinl83** [comment]
@AndreyKozlov1984 thoughts on this>
