### ISSUE TITLE
Turn off devtools messages in autocrop

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#497]
https://app.netlify.com/sites/landscape/deploys/5e14d83fbac6bb37d92ab5f9

2:19:15 PM: DevTools listening on ws://127.0.0.1:34607/devtools/browser/0880c3f3-ccfc-43a7-b9b5-44aa3ecdbf73
2:19:15 PM: DevTools listening on ws://127.0.0.1:36769/devtools/browser/11486af8-f65f-4c8f-b4a7-8970d358ad86
2:19:15 PM: DevTools listening on ws://127.0.0.1:45959/devtools/browser/23084918-3fbd-42d1-97df-75dadcaf3d8f
2:19:15 PM: DevTools listening on ws://127.0.0.1:38783/devtools/browser/2d7c6b5c-75f7-4d4e-b503-464f781f6bb1
2:19:15 PM: DevTools listening on ws://127.0.0.1:35819/devtools/browser/b894c76b-c0e9-4c7a-b199-593e2b724585

**Comment by AndreyKozlov1984** [comment]
I can suppress exactly this message from logs. I am not able to block puppeteer from reporting this stuff, but I already intercept all messages for the landscapeapp deployment.

**Comment by dankohn** [comment]
OK. Those messages just started showing up a couple weeks ago when you did your last update.
