### ISSUE TITLE
Misplaced logo on https://landscape.cncf.io/images/members.png

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#498]
![image](https://user-images.githubusercontent.com/3083270/72171622-5a8a8480-33a1-11ea-9232-668e44b45476.png)

Oddly, the issue only appears on the PNG, but not on the PDF or interactive version

**Comment by AndreyKozlov1984** [comment]
Something is different with rendering in chromium, the solution was simple - specify a width of a given image.

**Comment by dankohn** [comment]
Fixed with https://github.com/cncf/landscape/commit/a8c2984469adf34865e8e350104d6f17ae5e7239
