### ISSUE TITLE
Redo all artwork logos

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#510]
And include the project name of the logo in Title.

**Comment by AndreyKozlov1984** [comment]
@dankohn please review remaining pull requests.
https://github.com/ucfoundation/ucf-landscape/pull/38
https://github.com/openjs-foundation/openjsf-landscape/pull/11
https://github.com/lf-energy/lfenergy-landscape/pull/5
https://github.com/cdfoundation/cdf-landscape/pull/57
https://github.com/hyperledger-landscape/hl-landscape/pull/34
https://github.com/AcademySoftwareFoundation/aswf-landscape/pull/49
After that the issue should be finished.

**Comment by dankohn** [comment]
Done, thanks.
