### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by jmertic** [cncf/landscapeapp#532]
Hi!

Not sure if this has been considered, but would it be possible to support Gitlab? I'm starting to see a few repos only over there popup...

**Comment by jmertic** [comment]
Adding feedback from an LF project looking to use this...

> > What I have learned is that this particular technical process does not support Gitlab. But, if you want to create a mirror of the repo on Github, that should work fine. How does that sound?
>
> Not good. Hey, we are talking about a  link. I cannot believe that links (to gitlab) are not supported... If this is the case the technical process should be adapted.
Creating a mirror does not make any sense - sorry.

**Comment by caniszczyk** [comment]
@jmertic which LF project uses GitLab? :)

**Comment by jmertic** [comment]
The feedback came from someone in CIP - not sure if they currently use it
or plan to.

I do also think that CHAOSS is leaning towards GitLab.

**Comment by ncaidin** [comment]
CIP currently uses Gitlab.

**Comment by jennydove** [comment]
I've had a number of projects that use GitLab want to be listed as well. Even if we can't pull anything from them, allowing gitlab links as "additional_repos" without erroring out would be a good start.

**Comment by jordinl83** [comment]
@jennydove You can use `other_repo_url` instead of `repo_url`, it should not error out but it won't fetch any information regarding the repo either. This is for the main repo, not for `additional_repos`, but I could also add support for `other_repo_url` inside `additional_repos`.

**Comment by jennydove** [comment]
Oh that would be great!

**Comment by jordinl83** [comment]
@jennydove changed the code to accept gitlab repos (or any URL really) for `additional_repos`. I've also changed it so you can use `repo_url` for gitlab instead of `other_repo_url`, that's both for the main repo and additional repos.

**Comment by jennydove** [comment]
amazing, thank you!
