### ISSUE TITLE
Optionally hide market cap and funding banner

### ISSUE THREAD

**Issue by brianwarner** [cncf/landscapeapp#544]
I'd like to request consideration for an option that would enable a landscape manager to hide the market cap and funding banner.  Thank you!

**Comment by AndreyKozlov1984** [comment]
I'm going to work on it, do you also have a specific landscape in mind so I would set those settings there?

**Comment by brianwarner** [comment]
Thank you, Andrey!  The landscape is this one: https://github.com/openjs-foundation/openjsf-landscape

**Comment by brianwarner** [comment]
Thank you both!

**Comment by AndreyKozlov1984** [comment]
@brianwarner you are welcome, just for your information, https://landscape.openjsf.org/format=card-mode has been updated.
