### ISSUE TITLE
Don't fail when GitHub description is empty

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#566]
See https://github.com/lfph/lfph-landscape/pull/4#issuecomment-632935542

**Comment by jordinl83** [comment]
Don't think the failures related to the linked PR have anything to do with empty descriptions. It seems that doing requests to github related to a github repo returned a 500, so this could indicate the errors were on github.

**Comment by dankohn** [comment]
Closing as non-replicable.
