### ISSUE TITLE
Report errors on all landscapes when running daily update

### ISSUE THREAD

**Issue by jordinl83** [cncf/landscapeapp#568]
We don't have any visibility on any failures produced when running the daily `npm run update` to refresh the data for landscapes other than CNCF.

In fact, I added an the `Data Refreshed` column on [landscapes-dev.netlify.app](https://landscapes-dev.netlify.app), that should show the latest time this task was run on a landscape. It's not showing on three of the landscapes, which probably means the task fails for these landscapes.

We should report any failures somewhere, I see a couple of options, either post them on the `landscapes-logs` Slack channel or open an issue on the relevant github repo.

**Comment by jordinl83** [comment]
Considering logging output to https://www.papertrail.com

**Comment by dankohn** [comment]
This is still reporting updates that finish with SUCCESS such as https://cloud-native.slack.com/archives/C014ELGS7PU/p1590819922000200. Please only report ones that end in FAILURE.
