### ISSUE TITLE
Allow use of repo_org instead of repo_url

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#582]
When a repo_org is listed, please fetch and aggregate all repos in that org.

**Comment by AndreyKozlov1984** [comment]
nice idea. What about latest commit, first commit , etc, take it as min / max ? What about contributors ? License ?30.05.2020, 23:30, "Dan Kohn" <notifications@github.com>:
When a repo_org is listed, please fetch and aggregate all repos in that org.

**Comment by dankohn** [comment]
@jordinl83 already implemented this with each repo selected separately so I'm asking him to do this one as well.

**Comment by jordinl83** [comment]
@dankohn `github_org` perhaps?

**Comment by dankohn** [comment]
`project_org` please
