### ISSUE TITLE
Fix `EADDRINUSE: address already in use :::45678` error on Netlify

### ISSUE THREAD

**Issue by jordinl83** [cncf/landscapeapp#589]
Been seeing this error in a few builds:

```
7:24:48 AM: Error: listen EADDRINUSE: address already in use :::45678
7:24:48 AM:     at Server.setupListenHandle [as _listen2] (net.js:1313:16)
7:24:48 AM:     at listenInCluster (net.js:1361:12)
7:24:48 AM:     at Server.listen (net.js:1447:7)
7:24:48 AM:     at startServer (/opt/repo/package/node_modules/react-snap/index.js:613:12)
7:24:48 AM:     at run (/opt/repo/package/node_modules/react-snap/index.js:639:50)
7:24:48 AM:     at main (/opt/repo/package/tools/prerender.js:62:11)
7:24:48 AM:     at Object.<anonymous> (/opt/repo/package/tools/prerender.js:80:1)
7:24:48 AM:     at Module._compile (internal/modules/cjs/loader.js:1200:30)
7:24:48 AM:     at Module._compile (/opt/repo/package/node_modules/pirates/lib/index.js:99:24)
7:24:48 AM:     at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
7:24:48 AM: Emitted 'error' event on Server instance at:
7:24:48 AM:     at emitErrorNT (net.js:1340:8)
7:24:48 AM:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
7:24:48 AM:   code: 'EADDRINUSE',
7:24:48 AM:   errno: -98,
7:24:48 AM:   syscall: 'listen',
7:24:48 AM:   address: '::',
7:24:48 AM:   port: 45678
7:24:48 AM: }
```

https://app.netlify.com/sites/openjsf-landscape/deploys/5ed5e21eecad9e0007e9001a

**Comment by AndreyKozlov1984** [comment]
I've fixed this in the master02.06.2020, 08:27, "Jordi Noguera" <notifications@github.com>:
Been seeing this error in a few builds:
7:24:48 AM: Error: listen EADDRINUSE: address already in use :::45678
7:24:48 AM:     at Server.setupListenHandle [as _listen2] (net.js:1313:16)
7:24:48 AM:     at listenInCluster (net.js:1361:12)
7:24:48 AM:     at Server.listen (net.js:1447:7)
7:24:48 AM:     at startServer (/opt/repo/package/node_modules/react-snap/index.js:613:12)
7:24:48 AM:     at run (/opt/repo/package/node_modules/react-snap/index.js:639:50)
7:24:48 AM:     at main (/opt/repo/package/tools/prerender.js:62:11)
7:24:48 AM:     at Object.<anonymous> (/opt/repo/package/tools/prerender.js:80:1)
7:24:48 AM:     at Module._compile (internal/modules/cjs/loader.js:1200:30)
7:24:48 AM:     at Module._compile (/opt/repo/package/node_modules/pirates/lib/index.js:99:24)
7:24:48 AM:     at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
7:24:48 AM: Emitted 'error' event on Server instance at:
7:24:48 AM:     at emitErrorNT (net.js:1340:8)
7:24:48 AM:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
7:24:48 AM:   code: 'EADDRINUSE',
7:24:48 AM:   errno: -98,
7:24:48 AM:   syscall: 'listen',
7:24:48 AM:   address: '::',
7:24:48 AM:   port: 45678
7:24:48 AM: }

https://app.netlify.com/sites/openjsf-landscape/deploys/5ed5e21eecad9e0007e9001a
