### ISSUE TITLE
Support adding text to logos in autocrop

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#629]
For lots of logos like the ones in https://landscape.lfph.io/category=pha-deployed-app&format=card-mode&grouping=category we add text below an SVG. Add a new mode to autopcrop to support adding that text and then call Inkscape (or similar) to convert the text to objects.

Note @jmertic implemented this in bash: https://github.com/jmertic/landscape-tools/blob/master/makememberprojectlogos.sh

**Comment by jmertic** [comment]
Thanks @dankohn !

CloudConvert has a similar API which could be used instead of Inkscape, but does have a limit of 25 conversions a day.

**Comment by AndreyKozlov1984** [comment]
I think the best approach would be to add some parameters and then add them to the UI. Working on that part. I've found a good library for that purpose - https://github.com/shrhdk/text-to-svg and so far it generates a nice `path` element

**Comment by AndreyKozlov1984** [comment]
Ok, I've got a good progress in the automatic mode,

![image](https://user-images.githubusercontent.com/230982/85691350-55f62600-b6cc-11ea-8b30-4b8601f75330.png)

Or

![image](https://user-images.githubusercontent.com/230982/85691427-6a3a2300-b6cc-11ea-9181-389c22300cc3.png)

Or

![image](https://user-images.githubusercontent.com/230982/85691582-8b9b0f00-b6cc-11ea-93fb-38555c013592.png)

But I am sure that people may want to manually change the color, text scale, move it a bit to the top or a bit to the bottom, or have 2 lines of text. I want to make a command line tool with an interactive mode, which would start a puppeteer and draw a very simple UI, like we have in svg-autocrop-serverless which would allow to basically drag and drop the text as well as to zoom it.

**Comment by AndreyKozlov1984** [comment]
Custom font:

![image](https://user-images.githubusercontent.com/230982/85695120-a753e480-b6cf-11ea-8523-52217fb8e61e.png)

**Comment by AndreyKozlov1984** [comment]
I am also able to change the text height compared to its width, to make it looking better.

I guess I need to add the manual option to tune the final result to the svg-autocrop-serverless. Basically, I change only 3 parameters in the generated svg

![image](https://user-images.githubusercontent.com/230982/85695631-20ebd280-b6d0-11ea-99c2-0597c522e31b.png)

**Comment by jmertic** [comment]
Great progress!

One consideration is ensure that for a given company, the font sizing matches as svg-autocrop will change the positioning of the logo in the viewport which makes them look poor when placed side-by-side.

**Comment by dankohn** [comment]
I would restate @jmertic's point by saying that we want the text to fit on one line that's the width of the logo after autocropping. That'd what we do with all of our flag logos: https://landscape.lfph.io/category=pha-deployed-app&format=card-mode&grouping=no

@jmertic seems to do the same thing for https://landscape.openmainframeproject.org/format=card-mode&project=member

**Comment by AndreyKozlov1984** [comment]
Now the only remaining thing is to add some docs
