### ISSUE TITLE
Broken results on project_org

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#643]
Add `            project_org: 'https://github.com/opentrace-community'` to the lfph-landscape entry for [Singapore](https://github.com/lfph/lfph-landscape/blob/master/landscape.yml#L246) and you get a huge amount of garbage HTML output:

```
Fetching github entries
.......................Attempt #1 (MESSAGE: 404 - "\n\n\n\n\n<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n  <link rel=\"dns-prefetch\" href=\"https://github.githubassets.com\">\n  <link rel=\"dns-prefetch\" href=\"https://avatars0.githubusercontent.com\">\n  <link rel=\"dns-prefetch\" href=\"https://avatars1.githubusercontent.com\">\n  <link rel=\"dns-prefetch\" href=\"https://avatars2.githubusercontent.com\">\n  <link rel=\"dns-prefetch\" href=\"https://avatars3.githubusercontent.com\">\n  <link rel=\"dns-prefetch\" href=\"https://github-cloud.s3.amazonaws.com\">\n  <link rel=\"dns-prefetch\" href=\"https://user-images.githubusercontent.com/\">\n\n\n\n  <link crossorigin=\"anonymous\" media=\"all\" integrity=\"sha512-tNjDu1JoDfkjZINyRmi4t6GcEgOlz+NK5TFCJ5LFWA+ZwGV6uwzgPrP5qU+P9cAfHOca8JNF3Jl3IvkGnk+OPg==\"
```

**Comment by cfchase** [comment]
I was getting 404s when trying to getting github entries, specifically the contributors_size. Perhaps you're having a similar issue?  

I have gotten around it using this change: https://github.com/cfchase/landscapeapp/commit/1448af5f13f87e63fbaf3acd9b409f3267f6eefd.

Perhaps you've got a different issue, but just thought I'd offer it up.

**Comment by dankohn** [comment]
Thanks. @AndreyKozlov1984 and @jordinl83 will fix tomorrow.

**Comment by jordinl83** [comment]
We were using and endpoint used by the GitHub UI to fetch the count of contributors. GitHub is doing a redesign so that endpoint no longer exists, hence the errors.

We considered fetching the contributors count using the API, but it seems not to be very reliable for large repos. See https://developer.github.com/v3/repos/#list-repository-contributors

> GitHub identifies contributors by author email address. This endpoint groups contribution counts by GitHub user, which includes all associated email addresses. To improve performance, only the first 500 author email addresses in the repository link to GitHub users. The rest will appear as anonymous contributors without associated GitHub user information.

For Kubernetes using the API we get 3425 contributors, while the UI shows [2764](https://github.com/kubernetes/kubernetes).

We could use the API to count contributors, but I think that for projects that have contributors > 500, we will have to show "500+" instead of the calculated number.

**Comment by dankohn** [comment]
Yes, 500+ sounds OK.
--Dan Kohn <dan@linuxfoundation.org>+1-415-233-1000
General Manager, LF Public Health,lfph.io
dankohn.com or book on my calendar:dankohn.com/c  





On Wed, Jul 1, 2020 10:37 AM, Jordi Noguera notifications@github.com  wrote:


We were using and endpoint used by the GitHub UI to fetch the count of
contributors. GitHub is doing a redesign so that endpoint no longer exists,
hence the errors.

We considered fetching the contributors count using the API, but it seems not to
be very reliable for large repos. See 
https://developer.github.com/v3/repos/#list-repository-contributors

GitHub identifies contributors by author email address. This endpoint groups
contribution counts by GitHub user, which includes all associated email
addresses. To improve performance, only the first 500 author email addresses in
the repository link to GitHub users. The rest will appear as anonymous
contributors without associated GitHub user information.

For Kubernetes using the API we get 3425 contributors, while the UI shows 2764.

We could use the API to count contributors, but I think that for projects that
have contributors > 500, we will have to show "500+" instead of the calculated
number.
