### ISSUE TITLE
Add new formatting options

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#656]
We currently have 3 modes: landscape, card-mode, and logo-mode:

https://landscape.cncf.io/
https://landscape.cncf.io/format=card-mode
https://landscape.cncf.io/format=logo-mode

We want to add two new modes: `flat-mode` and `borderless-mode`. They should look like page 1 and 2 of:

[landscape-embed-redesign_v2.pdf](https://github.com/cncf/landscapeapp/files/4929139/landscape-embed-redesign_v2.pdf)

We also want to add a new mode called `condensed-card` that looks like the image on page 3. Finally, we want to add a `twitter` switch to be able to turn off Twitter.

So, in combination, we want to be able to have a URL like:

https://landscape.cncf.io/category=cncf-members&format=borderless-mode&grouping=category&twitter=no&condensed-card=yes

Cc @jmertic @ccraigross

**Comment by jmertic** [comment]
One other idea with these modes - it would be great if the output could be a png. Use-case is that I could embed in the member list in board decks with ease ( and potentially auto-refresh to update the image )

**Comment by dankohn** [comment]
Note that you can get that now if you put your members on a separate landscape page:

https://landscape.cncf.io/format=members
https://landscape.cncf.io/images/members.png

**Comment by jmertic** [comment]
Oh cool - maybe I should look into that. Thanks for the tip @dankohn !

**Comment by AndreyKozlov1984** [comment]
Regarding the mode #3 - we have a lot of potential information which can be displayed.
We have 2 charts, licenses, number of employees, and I think it is about 10 or even more different fields. Plus we support different screen sizes, mobile phones, tablets.

**Comment by dankohn** [comment]
We're mainly using `condensed-card` mode to show off members, which are always closed source, so we can ignore the charts, license, etc. and just show the data that the mockup shows. Also, please don't show the category, since that duplicates the information in the badge.

**Comment by AndreyKozlov1984** [comment]
How do I get a header "CNCF Members * Platinum " ?

**Comment by AndreyKozlov1984** [comment]
@dankohn white and grey backgrounds of logos - do we still have this ?

**Comment by dankohn** [comment]
Leave out that header. Always do white backgrounds.

**Comment by AndreyKozlov1984** [comment]
![s1](https://user-images.githubusercontent.com/230982/87879826-f8ac7680-c9e4-11ea-94e3-c275e5719533.png)

**Comment by dankohn** [comment]
Please also add a `background` key that can be set to any RGB value for the background color.

**Comment by dankohn** [comment]
Also, please remove switch to `card-mode` when someone clicks the "View the full interactive landscape" such as at the bottom of https://www.lfph.io/join/members/. It should link to https://landscape.lfph.io/category=lfph-members&format=card-mode&grouping=category not to https://landscape.lfph.io/category=lfph-members&format=borderless-mode&grouping=category

**Comment by jmertic** [comment]
I think we being able to add custom CSS, we likely don't need these additional formatting options. @AndreyKozlov1984 - you agree?

**Comment by AndreyKozlov1984** [comment]
We can easily embed custom css, thus lets close this now

**Comment by jmertic** [comment]
I can't close this :-( - Can you @AndreyKozlov1984 ?

**Comment by AndreyKozlov1984** [comment]
Done!
