### ISSUE TITLE
Update iframe resizer

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#661]
From https://github.com/lfph/lfph.io/issues/71: 

A few issues I noticed popping up on any page embedding the Landscape block. The block is pulling iframeResizer.js from landscape.lfph.io.

iframeResizer.js:8 [iFrameSizer][Host page: landscape] Deprecated: 'messageCallback' has been renamed 'onMessage'. The old method will be removed in the next major version.

DevTools failed to load SourceMap: Could not parse content for https://landscape.lfph.io/iframeResizer.map: Unexpected token < in JSON at position 0

The script also dumps quite a lot of console messages to the browser, so perhaps { log: false } could be set

![image](https://user-images.githubusercontent.com/3083270/88388057-c357ae00-cd81-11ea-9213-c579d7dc72da.png)

**Comment by dankohn** [comment]
@ibrahimhaddad  got the error when he did yp:

Your app is compiled in production mode in /dist. It's ready to roll!
sed: 1: "/Users/ibrahimhaddad/Do ...": command i expects \ followed by text

**Comment by AndreyKozlov1984** [comment]
Ok, about to fix this30.07.2020, 15:15, "Dan Kohn" <notifications@github.com>:
@ibrahimhaddad  got the error when he did yp:
Your app is compiled in production mode in /dist. It's ready to roll!
sed: 1: "/Users/ibrahimhaddad/Do ...": command i expects \ followed by text
