### ISSUE TITLE
Dex is not recognized as an open-source project

### ISSUE THREAD

**Issue by stuartpb** [cncf/landscapeapp#668]
I don't see anything wrong with [the downstream data for Dex](https://github.com/cncf/landscape/blob/master/landscape.yml#L359-L364), so it'd appear there's something wrong with the generator, because [Dex is listed as "Not Open Source"](https://landscape.cncf.io/selected=dex) even though [the repo is clearly published under the Apache License](https://github.com/dexidp/dex).

**Comment by dankohn** [comment]
Presence of a `repo_url` determines that a project is open source. 

Fixed with https://github.com/cncf/landscape/commit/98758b605c6e0f9c06de08568b42cf7868a2acad

https://landscape.cncf.io/format=card-mode&selected=dex

Sorry for the incorrect entry.
