### ISSUE TITLE
Deployment fails on ERROR '.git/HEAD does not exist'

### ISSUE THREAD

**Issue by next-mark** [cncf/landscapeapp#680]
We are trying to create our own landscape and host it on our Azure subscription.  We started the instructions found here: https://github.com/cncf/landscapeapp#creating-a-new-landscape The instructions mention using an existing landscape as a starting point.
> copy over files from a simpler landscape like https://github.com/graphql/graphql-landscape 

When we deploy this `graphql-landscape` on an Azure Node.js App Service, the bundle seems to build correctly but when the application is started it fails on a missing git repository which is not clear why.  The build log shows:
```
Your app is compiled in production mode in /dist. It's ready to roll!
/tmp/8d889725a0a2033/node_modules/interactive-landscape/node_modules/git-branch/index.js:36
    throw new Error('.git/HEAD does not exist');
```
I don't mind creating a git repository if the Landscape App uses this for a purpose, however since the build is using the upstream `interactive-landscape` npm package, it's not clear to me where the git repository would need to be created.  I did try to initiate a git repository in the startup location of the application (`/home/site/wwwroot` on Azure, AFAIK) but that had no effect.

How can we overcome this failing requirement on a git repository?

**Comment by AndreyKozlov1984** [comment]
This was never designed for Azure cloud, although we want to support a simple node.js hosting
