### ISSUE TITLE
Fetch crunchbase delisted status

### ISSUE THREAD

**Issue by AndreyKozlov1984** [cncf/landscapeapp#7]
When a company has a stock ticker and IPO status is `delisted`, treat the stock ticker as null.

https://www.crunchbase.com/organization/octo-technology#section-overview
https://www.crunchbase.com/organization/rackspace#section-overview

Then, look at whether you can clear out the `stock_ticker: null` entries from landscape.yml/

**Comment by jordinl83** [comment]
Reopening as Red Hat is not correctly marked as delisted. Also, I'll add a script to automatically remove entries that have `stock_ticker: null` but the stock ticker from Crunchbase can be found on Yahoo Finance.
