### ISSUE TITLE
Incorporate separate Googlebot JS into main package

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#71]

**Comment by dankohn** [comment]
https://www.google.com/webmasters/tools/googlebot-fetch-details?hl=en&authuser=0&siteUrl=https://landscape.cncf.io/&path=selected%3Drook&timestamp=1546386930379

**Comment by ZeusTheTrueGod** [comment]
`less node_modules/\@babel/preset-env/data/plugins.json`
So that is a file which contains which features are supported by chrome and which are not.
arrow function is certainly not supported there. The plan is to apply babel one more time to support chrome 41 from the node_modules

**Comment by dankohn** [comment]
Here's much more detail on creating 2 versions of the JS, one for evergreen and one for GoogleBot:
https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

Use es-check to decide what node_modules to transpile:
https://levelup.gitconnected.com/lessons-learned-from-a-year-of-fighting-with-webpack-and-babel-ce3b4b634c46

There are other good tricks in that article.

Here are a bunch more tricks for reducing size:
https://github.com/GoogleChromeLabs/webpack-libs-optimizations

**Comment by ZeusTheTrueGod** [comment]
As I understand, you want the googlebot to be generated from the webpack.config.prod.js, not via a command line extra transpile

**Comment by ZeusTheTrueGod** [comment]
Yes, that is pointless at this moment.
