### ISSUE TITLE
Stuck setting up a new landscape - issues in package directory

### ISSUE THREAD

**Issue by next-mark** [cncf/landscapeapp#711]
While trying to create a new landscape, we get stuck setting up our own environment using the `interactive-landscape` package due to issues in the package directory.  Our goal is to use this package in our private development environment so that we can make changes in the `landscape.yml` file and quickly see these changes reflected in our development environment.

We started with the following https://github.com/cncf/landscapeapp#creating-a-new-landscape instructions, and have the following `package.json`:
```js
{
  "name": "new-interactive-landscape",
  "version": "1.0.0",
  "description": "New interactive visualization",
  "engines": {
    "npm": ">=3",
    "node": ">= 10.5"
  },
  "scripts": {
    "start": "npm run build",
    "build": "npm config set scripts-prepend-node-path true;  npm explore interactive-landscape -- npm run build"
  },
  "dependencies": {
    "interactive-landscape": "1.0.523"
  },
  "keywords": []
}
```
Note: we trigger `npm install` manually to install the `interactive-landscape` dependency.  Also we set the environment variable `PROJECT_PATH` manually to the path in which the `package.json` and other project files are stored.  Our environment variable is set to the following `PROJECT_PATH=/xxx/xxx/xxx/new-landscape`  (The template `package.json` had this set dynamically basis `export PROJECT_PATH=\"$PWD\"` but that gave inconsistent result across different OS's) 

After we start our project with `npm start` it calls on the `interactive-landscape` through the `npm explore` command.  The subsequent `npm run build` fails with the following message:
```
Usage Error: The nearest package directory (/xxx/xxx/xxx/new-landscape/node_modules/interactive-landscape) doesn't seem to be part of the project declared in /xxx/xxx/xxx/new-landscape.

- If the project directory is right, it might be that you forgot to list node_modules/interactive-landscape as a workspace.
- If it isn't, it's likely because you have a yarn.lock or package.json file there, confusing the project root detection.

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
```
After this we tried to add the `interactive-landscape` as a workspace by adding the following in the root of our `package.json`, but it had no effect:
```js 
  "private": true,
  "workspaces": [
    "interactive-landscape"
  ],
```
(also tried the same with `node_modules/interactive-landscape` as the name of the workspace)

What is the correct structure needed for this to work?

P.s. I did read this issue https://github.com/cncf/landscapeapp/issues/704 and realised that the author of the issue didn't mention where they got stuck. So I also hope this issue would highlight what could be changed in the documentation for novice users to get started.

**Comment by jordinl83** [comment]
We don't run our landscapes this way... [cncf/landscapeapp](https://github.com/cncf/landscapeapp) should not be a dependency of your landscape, it should be cloned locally and the commands executed from the folder where it's been cloned. For instance:

```
git clone https://github.com/cncf/landscapeapp
cd landscapeapp
yarn install
PROJECT_PATH=/path/to/your/landscape yarrn build
```

Probably you'll also need to set a bunch of environment variables in order to fetch data from Crunchbase, GitHub and other sources.

**Comment by next-mark** [comment]
Ok thanks Jordi, we'll do that instead.

For your information: We tried to avoid taking cloning the landscape-app, which is why we preferred this method.  The landscape specific `package.json` as included in many landscape repositories gave us the impression this was a workable workflow using `npm explore`
