### ISSUE TITLE
Support gitlab.com as host in repo_url

### ISSUE THREAD

**Issue by maoo** [cncf/landscapeapp#712]
Right now, all items must define a unique `repo_url`, pointing to a github.com repository URL; if not, the landscape build will fail with: `item ABC has an invalid repo XYZ` or `Duplicate repo: ABC on XYZ at path 123 / 456`

At [FINOS](https://landscape.finos.org/), we'd like to have the ability to add links to our projects hosted on `gitlab.com`; is it possible to relax (or extend) the `repo_url` validation, in order to allow our use case to work?

Thanks in advance!

**Comment by jordinl83** [comment]
@maoo What is the goal? Do you just want to show the repo URL in the modal or do you also want to fetch info related to the repo from gitlab? 

I'm asking because the way it works with GitHub, we fetch repo info from GitHub's API using the API key `GITHUB_KEY`. But with GitLab, this is more complex, given a repo could be hosted on gitlab.com or it could be in a self-hosted instance of gitlab. In fact, there could be repos hosted in different instances of gitlab...

Also Maurizio, you mentioned gitlab.com on the issue title, but I see gitlab.legend.finos.org in your PR. Which one is it?

@caniszczyk @jmertic I see another issue asked for gitlab support https://github.com/cncf/landscapeapp/issues/532. Do we want to close one of the issues?

**Comment by jordinl83** [comment]
By the way, my suggestion would be to just show the link and not fetch info from repos on a self-hosted  gitlab instance, otherwise it gets complicated.

**Comment by jmertic** [comment]
Yes - both are one in the same.

I think largely for Github we leverage it for repo commits/license/stars/forks, right? It might be prudent to consider LFX Insights support and route the data retrieval through there; that would also help in the aggregation of stats across a set of repos.

**Comment by AndreyKozlov1984** [comment]
Can we add a gitlab_url field and just show it as a link without fetching any information ? Is gitlab a public or a private repo in this case ?

**Comment by maoo** [comment]
> Can we add a gitlab_url field and just show it as a link without fetching any information ? 

Yes, as long as `repo_url` is not mandatory.

> Is gitlab a public or a private repo in this case ?

Public.

Thanks!

**Comment by maoo** [comment]
> Also Maurizio, you mentioned gitlab.com on the issue title, but I see gitlab.legend.finos.org in your PR. Which one is it?

Would be great to be able to support both (gitlab.com and hosted instances); if not possible, just gitlab.com (we're in the process of moving from self-hosted to gitlab.com . TY!

**Comment by jordinl83** [comment]
@maoo for the time being I've added `other_repo_url` which you can use for repos from your self-hosted gitlab, we won't fetch any info regarding that repo (such as contributors, stars, ...) but the repo will be shown on the modal.

Later on we can investigate fetching those stats from repos hosted on gitlab.com.

**Comment by maoo** [comment]
> @maoo for the time being I've added `other_repo_url` which you can use for repos from your self-hosted gitlab, we won't fetch any info regarding that repo (such as contributors, stars, ...) but the repo will be shown on the modal.
> 
> Later on we can investigate fetching those stats from repos hosted on gitlab.com.

Awesome, thanks @jordinl83 ! So, if I define a `other_repo_url`, but no `repo_url`, will it still fail?

**Comment by jordinl83** [comment]
@maoo It should work. `repo_url` is for repos hosted on github.com, which will attempt to fetch repo info from github. `other_repo_url` is for non-github repos and no info will be attempted to fetch. You can only use one or the other on the same item.

**Comment by maoo** [comment]
> @maoo for the time being I've added `other_repo_url` which you can use for repos from your self-hosted gitlab, we won't fetch any info regarding that repo (such as contributors, stars, ...) but the repo will be shown on the modal.
> 
> Later on we can investigate fetching those stats from repos hosted on gitlab.com.

It works, thanks a lot! I guess we can close this issue.
