### ISSUE TITLE
Cross linking of CNCF and CDF landscapes

### ISSUE THREAD

**Issue by steveonjava** [cncf/landscapeapp#716]
In discussions between the CNCF and CDF groups with Chris, Priyanka, Tracy, and myself, we would like to provide better visibility of these two landscapes with each other since there is a lot of overlap.

We had two ideas on how to showcase this to users:

1. Put a box for the CDF inside of the Continuous Integration and Delivery box in the CNCF landscape (and do something similar on the CDF side)
2. Embed the landscape similar to how Serverless is embedded in the CNCF landscape (so a thumbnail version of the landscape that you can click on to navigate)

For reference, here are the landscapes we would like to do cross-linking on:

- https://landscape.cncf.io/
- https://landscape.cd.foundation/

What is the best way to accomplish this?

**Comment by jordinl83** [comment]
@steveonjava I think the best and easiest would be `2.`. I could modify the component we use on the CNCF landscape to link to the other landscapes, to accept an external URL and the image preview.

**Comment by steveonjava** [comment]
That sounds great.

**Comment by jordinl83** [comment]
@steveonjava added link to CNCF Landscape, see [PR](https://github.com/cdfoundation/cdf-landscape/pull/96) and [Review App](https://deploy-preview-96--cdf-landscape.netlify.app/). I've used the landscape preview as the image, but it could be any image really, such as the CNCF logo. Haven't rearranged the categories because I wasn't sure where the landscape link should go.

**Comment by steveonjava** [comment]
That looks perfect for pointing from the CDF Landscape to the CNCF.  How will it look in the reverse direction to point from the CNCF Landscape to the CDF?

**Comment by jordinl83** [comment]
@steveonjava see https://deploy-preview-2064--landscape.netlify.app/

**Comment by steveonjava** [comment]
It looks great, and I saw that you pushed it live on both the CDF and CNCF landscape pages.  Thanks for implementing this!
