### ISSUE TITLE
Create filter for "Industry" and Organization Type

### ISSUE THREAD

**Issue by caniszczyk** [cncf/landscapeapp#722]
I would like to be able to filter by Industry and Organization type

I don't know if Crunchbase API has this information, otherwise we can add metadata to the landscape.yml

Industry can probably pull BLS: https://www.bls.gov/iag/tgs/iag_index_alpha.htm

**Comment by caniszczyk** [comment]
organization type is like "Academic" "Non Profit" "For Profit" etc

**Comment by jordinl83** [comment]
Closed via https://github.com/cncf/landscapeapp/commit/6de44ddd9acf0fb2efc4e424b4d68757f299c18d
