### ISSUE TITLE
Download png/pdf file locally without crunchbase API key

### ISSUE THREAD

**Issue by gromanmartin** [cncf/landscapeapp#739]
Hello, I am running your app locally just to get nice landscape picture of our organization. I was wondering if there is any way to generate the png or pdf file of the landscape without having to use crunchbase API key? I managed to get together a yaml file and I can view it in dev mode, I would just like to get the png/pdf file, but cant figure out how, because the build will fail as I do not have the crunchbase key. And it is impossible to download the files in dev mode.
I have very limited knowledge of js, so any help is greatly appreciated. I am running the app in VirtualBox, if that matters.
Cheers, M.

**Comment by jordinl83** [comment]
@gromanmartin assuming you can run the app locally, I think you could try executing from the command line: `yarn build-next && yarn remove-dist && yarn copy-dist && yarn stop-old-ci && yarn start-ci && yarn render-landscape`. This should generate the screenshots and save them to your landscape directory under `dist/images`

**Comment by gromanmartin** [comment]
@jordinl83 Brilliant, simple and beautiful, just like this app. Thanks a lot!

**Comment by jordinl83** [comment]
@gromanmartin I'm curious how did you manage to get it working without Crunchbase?

**Comment by gromanmartin** [comment]
@jordinl83 I found a small workaround, that only by editing `processed_landscape.yml` you can make it work without ever needing to build it, so I have gitlab repo, where I edit the yaml file and whenever I make a change I just pull it and restart localhost. 
The other yaml file `landscape.yml` I have commented out and dont use at all.
It only works for dev mode, but I dont mind that, as I am mostly interested in the generated picture. Also I am playing around with fork of this project mentioned in [issue #704](https://github.com/cncf/landscapeapp/issues/704), but it is very slow, since I know basically nothing about js.

**Comment by jordinl83** [comment]
@gromanmartin makes sense. Hopefully at some point we will address these issues so you don't need any workarounds to run a landscape.
