### ISSUE TITLE
Nightly update should create .nvmrc file

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#74]
The Netlify build is still using Node 10.5. Please modify the nightly build to do a `node -v  > .nvmrc` as recommended in https://www.netlify.com/docs/

**Comment by ZeusTheTrueGod** [comment]
This is is a great idea to have a single place where we specify a node version.
can not we just create an .nvmrc file in every repo ? 1 upstream and 2 downstreams.

**Comment by dankohn** [comment]
Let's just manually set it in landscapeapp and have the nightly build set the same in downstream repos.

**Comment by ZeusTheTrueGod** [comment]
Ok
