### ISSUE TITLE
Create an own 'offline' landscape

### ISSUE THREAD

**Issue by mambax** [cncf/landscapeapp#791]
Hi all

I'd like to draw my own landscape at home 🖼️ 

I can not find a guide, is that a use case? 

How could I render my own small landscape at home by editing the `landscape.yml` and `npm run start`-ing it? With render I mean

* Edit landscape.yml (or some other YML)
* Build (outcome is an HTML page)
* Host somewhere, e.g. on GitHub Pages

Thank you for pointers 🤝

**Comment by jordinl83** [comment]
@mambax It's explained in the [README](https://github.com/cncf/landscapeapp/blob/master/README.md)
