### ISSUE TITLE
Images for sections 

### ISSUE THREAD

**Issue by jmertic** [cncf/landscapeapp#819]
Hi!

So I'm trying to be clever and put the badges for each of the Zowe Conformance programs next to the list of icons for each offering. My hacks don't seem to be taking well...

https://6266d9e1547fcf058cc09c13--omp-landscape.netlify.app/zowe-conformant

Let me know how I could fix this :-). PR is at https://github.com/openmainframeproject/omp-landscape/pull/434

**Comment by jmertic** [comment]
You got it @AndreyKozlov1984 - that's exactly it :-)

**Comment by AndreyKozlov1984** [comment]
Do you want your stickers to be clickable? I made a top left one just as a LandscapeInfo with an image inside

**Comment by jmertic** [comment]
They don't need to be clickable
