### ISSUE TITLE
how to run landscapeapp locally step by step?

### ISSUE THREAD

**Issue by Black-Gold** [cncf/landscapeapp#828]
### run landscapeapp locally step by step

The README.md about Installing Locally is not work!
How to run development on local Linux step by step with the latest version? I am very interested in this project, please advise! Looking forward to your reply!

**Comment by moise3** [comment]
> ### run landscapeapp locally step by step
> 
> The README.md about Installing Locally is not work! How to run development on local Linux step by step with the latest version? I am very interested in this project, please advise! Looking forward to your reply!

Me too... anyone could help us ?

**Comment by AndreyKozlov1984** [comment]
Hello!
Can you try `node server.js` in the cncf/landscape repo ? It will do everything for you! After few seconds the full web server is ready and you can preview on a port 8001, plus it rebuilds automatically on any change and does not require any local key to be installed

**Comment by AndreyKozlov1984** [comment]
Hi, I am updating readme, the goal is to completely get rid of any dependencies

**Comment by breezybaldwin** [comment]
@AndreyKozlov1984 I got this error when running `node:internal/validators:129
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Object.join (node:path:1081:7)
    at Server.<anonymous> (/Users/breezy/Documents/GitHub/landscapeapp/server.js:58:23)
    at Server.emit (node:events:379:20)
    at parserOnIncoming (node:_http_server:938:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}`
