### ISSUE TITLE
Consider displaying CLOMonitor report summary

### ISSUE THREAD

**Issue by tegioz** [cncf/landscapeapp#845]
Hi!

This is Sergio, one of the CLOMonitor's maintainers 👋

[CLOMonitor](https://clomonitor.io) is a tool that periodically checks open source projects repositories to verify they meet certain project health best practices. At the moment most of the projects in the CNCF and LF AI & DATA foundations are listed.

CLOMonitor is able to produce a nice SVG image that summarizes how the project is doing on each of the categories. We were thinking that it'd be great if this report summary could be displayed somehow for each project in the corresponding landscape.

We'd be happy to help with anything you need 🙂

/cc @cynthia-sg

<img width="1456" alt="report-summary" src="https://user-images.githubusercontent.com/1213902/197193539-09591643-2b40-4dac-9820-26f420260201.png">

**Comment by AndreyKozlov1984** [comment]
@caniszczyk any exact ideas where exactly to put the status? Can it be just a single number with a link to show more details ?

**Comment by tegioz** [comment]
Hi @AndreyKozlov1984

Would it be possible to display the report summary SVG image (the rectangle with the purple header shown in the comment above) with a link to the corresponding CLOMonitor page?

**Comment by tegioz** [comment]
You can get the link for the SVG image from any of the projects' pages in CLOMonitor (pink menu button on the top right corner). The image is rendered dynamically so it's always up to date.

**Comment by tegioz** [comment]
Hi! 👋

Friendly ping just to check how this was going 😇 Please let us know if we can help with anything!

**Comment by AndreyKozlov1984** [comment]
@tegioz let me get back to this, I am going to review this today

**Comment by AndreyKozlov1984** [comment]
@tegioz how do you recommend to search the project? By its github repo url? Because projects may have a bit different names, what approach would you recommend me to lookup an entry ? Say, there is a "Kubernetes" entry in the landscape.yml, how I can guess the svg name?

**Comment by tegioz** [comment]
Hi @AndreyKozlov1984!

There would be two urls involved, the SVG image and the destination link:

**SVG image**: https://clomonitor.io/api/projects/{FOUNDATION}/{PROJECT_NAME}/report-summary?theme={THEME}
**Destination link**: https://clomonitor.io/projects/{FOUNDATION}/{PROJECT_NAME}

- FOUNDATION can be `cncf` or `lfaidata`.
- THEME can be `dark` or `light`.

For the PROJECT_NAME, I would suggest adding an entry in the extra object in the `landscape.yml` file for each project, like it's done for devstats, etc. That way, if the -let's say- `clomonitor_name` is present in extra, you can build the urls and display the corresponding image linked to the CLOMonitor's project page and otherwise do nothing.

We'd be happy to create a PR to include all CLOMonitor projects names in the landscape config file and maintain them until we start using the `landscape.yml` as a data source for CLOMonitor (cncf/clomonitor#471 - it'd be great if you can take a look at that issue and share your thoughts to help things move forward 🙂).

Please let me know if this would work for you and we'll create the PR. Thanks!

**Comment by AndreyKozlov1984** [comment]
@tegioz so what exactly do you want to see for the `kubernetes` in a new field `clomonitor_name` inside extra ? please give me an example value and also an example svg url

**Comment by tegioz** [comment]
In the case of the Kubernetes project, it'd be something like:

```yaml
clomonitor_name: kubernetes
```

And the urls would be:

SVG: <https://clomonitor.io/api/projects/cncf/kubernetes/report-summary?theme=light>
Link (to project's page in CLOMonitor for more details): <https://clomonitor.io/projects/cncf/kubernetes>

You can build them from the `clomonitor_name` value using the urls templates I shared in my previous comment.

**Comment by tegioz** [comment]
Hi @AndreyKozlov1984

@cynthia-sg has just created a draft PR (cncf/landscape#2998) to add the CLOMonitor project name to all CNCF projects In the landscape configuration file.

**Comment by AndreyKozlov1984** [comment]
Awesome!
Before merging it, I have to work on 
<img width="348" alt="image" src="https://user-images.githubusercontent.com/230982/214559659-0557ceb4-365f-4fc3-966f-a110b9bf09cb.png">
this part, obviously I'll hide it and will try to replace with the downloaded svg image. I plan to update you today, PR looks fine so far.

**Comment by AndreyKozlov1984** [comment]
About to deploy

**Comment by tegioz** [comment]
It looks great @AndreyKozlov1984, thanks! 

Could you please add a link on the image to the corresponding CLOMonitor's project page? That would allow projects to quickly learn a bit more about how they can improve their score and would also help driving traffic to CLOMonitor 😇

The link for each project would be: `https://clomonitor.io/projects/{FOUNDATION}/{PROJECT_NAME}`

**Comment by AndreyKozlov1984** [comment]
Ok, I'll make an svg image as a link, with target=_blank

**Comment by AndreyKozlov1984** [comment]
I would like to ask @taylorwaggoner or @caniszczyk like do we need to adjust colors? I can certainly do a header in a different color.

<img width="880" alt="image" src="https://user-images.githubusercontent.com/230982/214840580-f23dea37-5b29-474b-ab88-61e1e0865037.png">

**Comment by tegioz** [comment]
You can also display it in dark mode if you prefer, by passing `?theme=dark` to the SVG url.

<img width="450" alt="svg-dark" src="https://user-images.githubusercontent.com/1213902/214841208-e8427f07-2ad5-47e0-8b8e-5ab527ab086f.png">

**Comment by AndreyKozlov1984** [comment]
@tegioz is this finished ?

**Comment by tegioz** [comment]
Yes! Thanks for adding the link!
