### ISSUE TITLE
Improve security of landscape websites by following best practice guidance

### ISSUE THREAD

**Issue by Boojapho** [cncf/landscapeapp#849]
The security of the landscape sites generated by the app should be improved by following best practices, including:

- [Content Security Policy](https://content-security-policy.com/) headers: restrict scripts, styles, img, connect, font, object, media, and forms to `self` or trusted sources (e.g. fonts.gstatic.com).  Don't allow framing.
- Add a [nonce](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce) to scripts/styles 
- Add [security headers](https://www.invicti.com/white-papers/whitepaper-http-security-headers/)

You can use https://observatory.mozilla.org/analyze/landscape.cncf.io to help scan.  Currently, the CNCF landscape is marked with a score of 0/100.

**Comment by AndreyKozlov1984** [comment]
I completely disagree with everything above. It is a statically generated site, with few lambda functions on a Netlify.

**Comment by AndreyKozlov1984** [comment]
More than that, if someone tries to intentionally add malicious data, it can be done only via GitHub pull request.
