### ISSUE TITLE
Googlebot still confused by obsolete entries

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#86]
https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Flandscape.cncf.io%2F&item_key=CAMYAiAB&hl=en

Under `Indexed, not submitted in sitemap`, Google has a number of obsolete entries like:
```
https://landscape.cncf.io/selected=lizard-fs
https://landscape.cncf.io/selected=turbine-labs
https://landscape.cncf.io/selected=snap-route
```
The problem is that all of these are valid under the new, tighter robots.txt rules and still display the homepage.

When an invalid value for `selected` is in the URL, let's do a 301 redirect to remove it (and in this case, go to `https://landscape.cncf.io/`).

**Comment by ZeusTheTrueGod** [comment]
We can generate the robots.txt with specifying absolutely every possible url like https://landscape.cncf.io/selected=kubernetes

**Comment by ZeusTheTrueGod** [comment]
And disabling all other urls

**Comment by dankohn** [comment]
I thought of that, but robots.txt has a 500 kB limit.

**Comment by ZeusTheTrueGod** [comment]
Because each line is max 100 bytes, we can have up to 5000 entries in robots.txt

**Comment by dankohn** [comment]
OK, I'm open to going that direction.

It still seems like http://landscape.cncf.io/shfhfhf should redirect to
http://landscape.cncf.io/. If we remove any incorrect parameters, than I'm
not there's any value to explicitly listing all legal URLs.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
Ok, I can not make any redirect other than from a javascript. i.e. `location.href="/"`

**Comment by ZeusTheTrueGod** [comment]
I'll try that one, may be google will be happy with it

**Comment by dankohn** [comment]
It seems like Google would be OK with that.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
It shouldn't look like: https://support.google.com/webmasters/answer/2721217?hl=en
